<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


/** ActionUpdateProducts - Update products in an order in the schedule */
class ActionUpdateProducts
{
    /**
     *
     * @var TypeUpdateProducts $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\TypeUpdateProducts')]
    public TypeUpdateProducts $type;

    /**
     *
     * @var ActionInput5 $input
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('input')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\ActionInput5')]
    public ActionInput5 $input;

    /**
     * @param  TypeUpdateProducts  $type
     * @param  ActionInput5  $input
     * @phpstan-pure
     */
    public function __construct(TypeUpdateProducts $type, ActionInput5 $input)
    {
        $this->type = $type;
        $this->input = $input;
    }
}