<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class ActionInput3
{
    /**
     *
     * @var Address $address
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('address')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\Address')]
    public Address $address;

    /**
     * @param  Address  $address
     * @phpstan-pure
     */
    public function __construct(Address $address)
    {
        $this->address = $address;
    }
}