<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


/** ActionSkipItem - Skip individual line items in an order */
class ActionSkipItem
{
    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\TypeSkipItem $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\TypeSkipItem')]
    public TypeSkipItem $type;

    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\ActionInput2 $input
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('input')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\ActionInput2')]
    public ActionInput2 $input;

    /**
     * @param  \Juo\AdminAPI\Models\Operations\TypeSkipItem  $type
     * @param  \Juo\AdminAPI\Models\Operations\ActionInput2  $input
     * @phpstan-pure
     */
    public function __construct(TypeSkipItem $type, ActionInput2 $input)
    {
        $this->type = $type;
        $this->input = $input;
    }
}