<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


/** ActionUpdatePaymentMethod - Update the payment method for a specific order in the schedule */
class ActionUpdatePaymentMethod
{
    /**
     *
     * @var TypeUpdatePaymentMethod $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\TypeUpdatePaymentMethod')]
    public TypeUpdatePaymentMethod $type;

    /**
     *
     * @var ActionInput4 $input
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('input')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\ActionInput4')]
    public ActionInput4 $input;

    /**
     * @param  TypeUpdatePaymentMethod  $type
     * @param  ActionInput4  $input
     * @phpstan-pure
     */
    public function __construct(TypeUpdatePaymentMethod $type, ActionInput4 $input)
    {
        $this->type = $type;
        $this->input = $input;
    }
}