<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


/** ActionChangeDate - Change the date of an order in the schedule */
class ActionChangeDate
{
    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\TypeChangeDate $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\TypeChangeDate')]
    public TypeChangeDate $type;

    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\ActionInput2 $input
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('input')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\ActionInput2')]
    public ActionInput2 $input;

    /**
     * @param  \Juo\AdminAPI\Models\Operations\TypeChangeDate  $type
     * @param  \Juo\AdminAPI\Models\Operations\ActionInput2  $input
     * @phpstan-pure
     */
    public function __construct(TypeChangeDate $type, ActionInput2 $input)
    {
        $this->type = $type;
        $this->input = $input;
    }
}