<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


/** ActionSkipOrder - Skip an order in the schedule */
class ActionSkipOrder
{
    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\TypeSkipOrder $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\TypeSkipOrder')]
    public TypeSkipOrder $type;

    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\ActionInput1 $input
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('input')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\ActionInput1')]
    public ActionInput1 $input;

    /**
     * @param  \Juo\AdminAPI\Models\Operations\TypeSkipOrder  $type
     * @param  \Juo\AdminAPI\Models\Operations\ActionInput1  $input
     * @phpstan-pure
     */
    public function __construct(TypeSkipOrder $type, ActionInput1 $input)
    {
        $this->type = $type;
        $this->input = $input;
    }
}