<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class ActionInput3
{
    /**
     * New date for the order (ISO 8601)
     *
     * @var \DateTime $newDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('newDate')]
    public \DateTime $newDate;

    /**
     * @param  \DateTime  $newDate
     * @phpstan-pure
     */
    public function __construct(\DateTime $newDate)
    {
        $this->newDate = $newDate;
    }
}