<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


/** ActionUpdateShipping - Update the shipping address for a specific order in the schedule */
class ActionUpdateShipping
{
    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\TypeUpdateShipping $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\TypeUpdateShipping')]
    public TypeUpdateShipping $type;

    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\ActionInput3 $input
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('input')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\ActionInput3')]
    public ActionInput3 $input;

    /**
     * @param  \Juo\AdminAPI\Models\Operations\TypeUpdateShipping  $type
     * @param  \Juo\AdminAPI\Models\Operations\ActionInput3  $input
     * @phpstan-pure
     */
    public function __construct(TypeUpdateShipping $type, ActionInput3 $input)
    {
        $this->type = $type;
        $this->input = $input;
    }
}