<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


/** ActionApplyDiscount - Apply a discount (code or manual) to an order in the schedule */
class ActionApplyDiscount
{
    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\TypeApplyDiscount $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\TypeApplyDiscount')]
    public TypeApplyDiscount $type;

    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\InputCode|\Juo\AdminAPI\Models\Operations\InputLineItem|\Juo\AdminAPI\Models\Operations\InputShipping $input
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('input')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\InputCode|\Juo\AdminAPI\Models\Operations\InputLineItem|\Juo\AdminAPI\Models\Operations\InputShipping')]
    public InputCode|InputLineItem|InputShipping $input;

    /**
     * @param  \Juo\AdminAPI\Models\Operations\TypeApplyDiscount  $type
     * @param  \Juo\AdminAPI\Models\Operations\InputCode|\Juo\AdminAPI\Models\Operations\InputLineItem|\Juo\AdminAPI\Models\Operations\InputShipping  $input
     * @phpstan-pure
     */
    public function __construct(TypeApplyDiscount $type, InputCode|InputLineItem|InputShipping $input)
    {
        $this->type = $type;
        $this->input = $input;
    }
}