<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class BillingPolicy
{
    /**
     *
     * @var BillingPolicyIntervalDay|BillingPolicyIntervalWeek|BillingPolicyIntervalMonth|BillingPolicyIntervalYear $interval
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('interval')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\BillingPolicyIntervalDay|\Juo\AdminAPI\Models\Operations\BillingPolicyIntervalWeek|\Juo\AdminAPI\Models\Operations\BillingPolicyIntervalMonth|\Juo\AdminAPI\Models\Operations\BillingPolicyIntervalYear')]
    public BillingPolicyIntervalDay|BillingPolicyIntervalWeek|BillingPolicyIntervalMonth|BillingPolicyIntervalYear $interval;

    /**
     *
     * @var int $intervalCount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('intervalCount')]
    public int $intervalCount;

    /**
     * $anchors
     *
     * @var array<BillingPolicyAnchor> $anchors
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('anchors')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Juo\AdminAPI\Models\Operations\BillingPolicyAnchor>')]
    public array $anchors;

    /**
     *
     * @var ?int $minCycles
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('minCycles')]
    public ?int $minCycles;

    /**
     *
     * @var ?int $maxCycles
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('maxCycles')]
    public ?int $maxCycles;

    /**
     * @param  BillingPolicyIntervalDay|BillingPolicyIntervalWeek|BillingPolicyIntervalMonth|BillingPolicyIntervalYear  $interval
     * @param  int  $intervalCount
     * @param  array<BillingPolicyAnchor>  $anchors
     * @param  ?int  $minCycles
     * @param  ?int  $maxCycles
     * @phpstan-pure
     */
    public function __construct(BillingPolicyIntervalDay|BillingPolicyIntervalWeek|BillingPolicyIntervalMonth|BillingPolicyIntervalYear $interval, int $intervalCount, array $anchors, ?int $minCycles = null, ?int $maxCycles = null)
    {
        $this->interval = $interval;
        $this->intervalCount = $intervalCount;
        $this->anchors = $anchors;
        $this->minCycles = $minCycles;
        $this->maxCycles = $maxCycles;
    }
}