<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


/** Cohort - Optional cohort definition. When present, returns a retention triangle or LTV-by-cohort matrix. */
class Cohort
{
    /**
     * The anchor event type, e.g. 'subscription:purchased'.
     *
     * @var string $anchorEvent
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('anchorEvent')]
    public string $anchorEvent;

    /**
     * Time grain for cohort periods.
     *
     * @var \Juo\AdminAPI\Models\Operations\PeriodGrainDay|\Juo\AdminAPI\Models\Operations\PeriodGrainWeek|\Juo\AdminAPI\Models\Operations\PeriodGrainMonth|\Juo\AdminAPI\Models\Operations\PeriodGrainYear $periodGrain
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('periodGrain')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PeriodGrainDay|\Juo\AdminAPI\Models\Operations\PeriodGrainWeek|\Juo\AdminAPI\Models\Operations\PeriodGrainMonth|\Juo\AdminAPI\Models\Operations\PeriodGrainYear')]
    public PeriodGrainDay|PeriodGrainWeek|PeriodGrainMonth|PeriodGrainYear $periodGrain;

    /**
     * Cohort measure: 'retention' (survival) or 'ltv' (cumulative LTV per subscriber).
     *
     * @var \Juo\AdminAPI\Models\Operations\MeasureRetention|\Juo\AdminAPI\Models\Operations\MeasureLtv $measure
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('measure')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\MeasureRetention|\Juo\AdminAPI\Models\Operations\MeasureLtv')]
    public MeasureRetention|MeasureLtv $measure;

    /**
     * Number of relative periods to compute (0..periods for calendar; 1..periods for order_sequence). Default 12.
     *
     * @var ?int $periods
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('periods')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $periods = null;

    /**
     * How relative periods are defined. 'calendar' (default): period N = N calendar grains after the anchor. 'order_sequence': period N = billing-order number (1-based; N=1 = initial purchase, N=2 = first renewal, etc.).
     *
     * @var \Juo\AdminAPI\Models\Operations\PeriodBasisCalendar|\Juo\AdminAPI\Models\Operations\PeriodBasisOrderSequence|null $periodBasis
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('periodBasis')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PeriodBasisCalendar|\Juo\AdminAPI\Models\Operations\PeriodBasisOrderSequence|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public PeriodBasisCalendar|PeriodBasisOrderSequence|null $periodBasis = null;

    /**
     * @param  string  $anchorEvent
     * @param  \Juo\AdminAPI\Models\Operations\PeriodGrainDay|\Juo\AdminAPI\Models\Operations\PeriodGrainWeek|\Juo\AdminAPI\Models\Operations\PeriodGrainMonth|\Juo\AdminAPI\Models\Operations\PeriodGrainYear  $periodGrain
     * @param  \Juo\AdminAPI\Models\Operations\MeasureRetention|\Juo\AdminAPI\Models\Operations\MeasureLtv  $measure
     * @param  ?int  $periods
     * @param  \Juo\AdminAPI\Models\Operations\PeriodBasisCalendar|\Juo\AdminAPI\Models\Operations\PeriodBasisOrderSequence|null  $periodBasis
     * @phpstan-pure
     */
    public function __construct(string $anchorEvent, PeriodGrainDay|PeriodGrainWeek|PeriodGrainMonth|PeriodGrainYear $periodGrain, MeasureRetention|MeasureLtv $measure, ?int $periods = null, PeriodBasisCalendar|PeriodBasisOrderSequence|null $periodBasis = null)
    {
        $this->anchorEvent = $anchorEvent;
        $this->periodGrain = $periodGrain;
        $this->measure = $measure;
        $this->periods = $periods;
        $this->periodBasis = $periodBasis;
    }
}