<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


/** DeleteSubscriptionsSubscriptionIdDiscountsDiscountIdResponseBody - Default Response */
class DeleteSubscriptionsSubscriptionIdDiscountsDiscountIdResponseBody
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var DeleteSubscriptionsSubscriptionIdDiscountsDiscountIdResource $resource
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('resource')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\DeleteSubscriptionsSubscriptionIdDiscountsDiscountIdResource')]
    public DeleteSubscriptionsSubscriptionIdDiscountsDiscountIdResource $resource;

    /**
     *
     * @var bool $deleted
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('deleted')]
    public bool $deleted;

    /**
     * @param  string  $id
     * @param  DeleteSubscriptionsSubscriptionIdDiscountsDiscountIdResource  $resource
     * @param  bool  $deleted
     * @phpstan-pure
     */
    public function __construct(string $id, DeleteSubscriptionsSubscriptionIdDiscountsDiscountIdResource $resource, bool $deleted)
    {
        $this->id = $id;
        $this->resource = $resource;
        $this->deleted = $deleted;
    }
}