<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


/** DeleteProductsProductIdVariantsVariantIdPlansResponseBody - Default Response */
class DeleteProductsProductIdVariantsVariantIdPlansResponseBody
{
    /**
     *
     * @var string $planId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('planId')]
    public string $planId;

    /**
     *
     * @var bool $removed
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('removed')]
    public bool $removed;

    /**
     * @param  string  $planId
     * @param  bool  $removed
     * @phpstan-pure
     */
    public function __construct(string $planId, bool $removed = true)
    {
        $this->planId = $planId;
        $this->removed = $removed;
    }
}