<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class DeleteProductsProductIdVariantsVariantIdPlansRequestBody
{
    /**
     * The subscription plan identifier
     *
     * @var string $planId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('planId')]
    public string $planId;

    /**
     * @param  string  $planId
     * @phpstan-pure
     */
    public function __construct(string $planId)
    {
        $this->planId = $planId;
    }
}