<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;

use Juo\AdminAPI\Utils\SpeakeasyMetadata;
class DeleteProductsProductIdRequest
{
    /**
     * The product identifier
     *
     * @var string $productId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=productId')]
    public string $productId;

    /**
     * Unique identifier of the tenant in the system (usually a store identifier)
     *
     * @var ?string $tenant
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=X-Tenant-ID')]
    public ?string $tenant = null;

    /**
     * @param  string  $productId
     * @param  ?string  $tenant
     * @phpstan-pure
     */
    public function __construct(string $productId, ?string $tenant = null)
    {
        $this->productId = $productId;
        $this->tenant = $tenant;
    }
}