<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;

use Juo\AdminAPI\Utils\SpeakeasyMetadata;
class DeleteSchedulesAdjustmentsAdjustmentIdRequest
{
    /**
     * The adjustment identifier
     *
     * @var string $adjustmentId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=adjustmentId')]
    public string $adjustmentId;

    /**
     * Unique identifier of the tenant in the system (usually a store identifier)
     *
     * @var ?string $tenant
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=X-Tenant-ID')]
    public ?string $tenant = null;

    /**
     * @param  string  $adjustmentId
     * @param  ?string  $tenant
     * @phpstan-pure
     */
    public function __construct(string $adjustmentId, ?string $tenant = null)
    {
        $this->adjustmentId = $adjustmentId;
        $this->tenant = $tenant;
    }
}