<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class DeliveryMethodLocalDelivery
{
    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\TypeLocalDelivery $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\TypeLocalDelivery')]
    public TypeLocalDelivery $type;

    /**
     * Contact phone number.
     *
     * @var string $phone
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('phone')]
    public string $phone;

    /**
     *
     * @var ?string $title
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('title')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $title = null;

    /**
     * Delivery instructions.
     *
     * @var ?string $instructions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('instructions')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $instructions = null;

    /**
     * @param  \Juo\AdminAPI\Models\Operations\TypeLocalDelivery  $type
     * @param  string  $phone
     * @param  ?string  $title
     * @param  ?string  $instructions
     * @phpstan-pure
     */
    public function __construct(TypeLocalDelivery $type, string $phone, ?string $title = null, ?string $instructions = null)
    {
        $this->type = $type;
        $this->phone = $phone;
        $this->title = $title;
        $this->instructions = $instructions;
    }
}