<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class DeliveryMethod
{
    /**
     *
     * @var ?PatchSubscriptionsSubscriptionIdType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PatchSubscriptionsSubscriptionIdType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PatchSubscriptionsSubscriptionIdType $type = null;

    /**
     * The title of the delivery method
     *
     * @var ?string $title
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('title')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $title = null;

    /**
     * The description of the delivery method
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $description = null;

    /**
     * @param  ?PatchSubscriptionsSubscriptionIdType  $type
     * @param  ?string  $title
     * @param  ?string  $description
     * @phpstan-pure
     */
    public function __construct(?PatchSubscriptionsSubscriptionIdType $type = null, ?string $title = null, ?string $description = null)
    {
        $this->type = $type;
        $this->title = $title;
        $this->description = $description;
    }
}