<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class DeliveryPolicy
{
    /**
     *
     * @var DeliveryPolicyIntervalDay|DeliveryPolicyIntervalWeek|DeliveryPolicyIntervalMonth|DeliveryPolicyIntervalYear $interval
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('interval')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\DeliveryPolicyIntervalDay|\Juo\AdminAPI\Models\Operations\DeliveryPolicyIntervalWeek|\Juo\AdminAPI\Models\Operations\DeliveryPolicyIntervalMonth|\Juo\AdminAPI\Models\Operations\DeliveryPolicyIntervalYear')]
    public DeliveryPolicyIntervalDay|DeliveryPolicyIntervalWeek|DeliveryPolicyIntervalMonth|DeliveryPolicyIntervalYear $interval;

    /**
     *
     * @var int $intervalCount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('intervalCount')]
    public int $intervalCount;

    /**
     * $anchors
     *
     * @var array<DeliveryPolicyAnchor> $anchors
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('anchors')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Juo\AdminAPI\Models\Operations\DeliveryPolicyAnchor>')]
    public array $anchors;

    /**
     * @param  DeliveryPolicyIntervalDay|DeliveryPolicyIntervalWeek|DeliveryPolicyIntervalMonth|DeliveryPolicyIntervalYear  $interval
     * @param  int  $intervalCount
     * @param  array<DeliveryPolicyAnchor>  $anchors
     * @phpstan-pure
     */
    public function __construct(DeliveryPolicyIntervalDay|DeliveryPolicyIntervalWeek|DeliveryPolicyIntervalMonth|DeliveryPolicyIntervalYear $interval, int $intervalCount, array $anchors)
    {
        $this->interval = $interval;
        $this->intervalCount = $intervalCount;
        $this->anchors = $anchors;
    }
}