<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class DeliveryPolicyAnchor
{
    /**
     *
     * @var DeliveryPolicyTypeWeekday|DeliveryPolicyTypeMonthday|DeliveryPolicyTypeYearday $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\DeliveryPolicyTypeWeekday|\Juo\AdminAPI\Models\Operations\DeliveryPolicyTypeMonthday|\Juo\AdminAPI\Models\Operations\DeliveryPolicyTypeYearday')]
    public DeliveryPolicyTypeWeekday|DeliveryPolicyTypeMonthday|DeliveryPolicyTypeYearday $type;

    /**
     *
     * @var int $day
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('day')]
    public int $day;

    /**
     *
     * @var ?int $month
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('month')]
    public ?int $month;

    /**
     *
     * @var ?int $cutoffDay
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('cutoffDay')]
    public ?int $cutoffDay;

    /**
     * @param  DeliveryPolicyTypeWeekday|DeliveryPolicyTypeMonthday|DeliveryPolicyTypeYearday  $type
     * @param  int  $day
     * @param  ?int  $month
     * @param  ?int  $cutoffDay
     * @phpstan-pure
     */
    public function __construct(DeliveryPolicyTypeWeekday|DeliveryPolicyTypeMonthday|DeliveryPolicyTypeYearday $type, int $day, ?int $month = null, ?int $cutoffDay = null)
    {
        $this->type = $type;
        $this->day = $day;
        $this->month = $month;
        $this->cutoffDay = $cutoffDay;
    }
}