<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class GetAnalyticsMetricsMetric
{
    /**
     * The metric key to send as `metric` on a query.
     *
     * @var string $key
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('key')]
    public string $key;

    /**
     * Broad shape of the number: count, sum, unique, gauge or ratio.
     *
     * @var string $kind
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('kind')]
    public string $kind;

    /**
     * The published API resource this number is about: customers, subscriptions, subscription-items, orders or order-items. Always equal to the part of `key` before the colon. This is what one unit of the metric means — `measuredOn` is the narrower question of what one source row is, and the two differ wherever a metric aggregates finer rows into a coarser figure.
     *
     * @var string $subject
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subject')]
    public string $subject;

    /**
     * What the number means.
     *
     * @var string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    public string $description;

    /**
     * Every load-bearing approximation in the number, so a caller can decide whether it matters to them. Never empty.
     *
     * @var array<string> $assumptions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('assumptions')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>')]
    public array $assumptions;

    /**
     * What one SOURCE ROW of this metric is: shop, subscriber, subscription, subscription_item, order or order_line. NOT what the number is about — read `subject` for that. `order-items:units` is measured on order_line rows and `orders:revenue` reports an order figure over the same rows, so both report a coarser figure than they measure. For a ratio this is the denominator's row grain. Note the request body's own `grain` is a different thing: the time bucket.
     *
     * @var string $measuredOn
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('measuredOn')]
    public string $measuredOn;

    /**
     * Whether values sum across time buckets: `additive`, `semi_additive` (use the bucket's last value) or `non_additive` (re-aggregate from the underlying set).
     *
     * @var string $additivity
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('additivity')]
    public string $additivity;

    /**
     * Whether an fx rate is applied at query time.
     *
     * @var bool $currencyConverted
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currencyConverted')]
    public bool $currencyConverted;

    /**
     * Internal identifier of the query shape that answers this metric.
     *
     * @var string $sourceModel
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sourceModel')]
    public string $sourceModel;

    /**
     * Legal `dimensions` entries. Anything else is a 400.
     *
     * @var array<string> $groupBy
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('groupBy')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>')]
    public array $groupBy;

    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\Filter $filter
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('filter')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\Filter')]
    public Filter $filter;

    /**
     * Legal `grain` values. Snapshot metrics accept only `total`, having no history to bucket.
     *
     * @var array<string> $grains
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('grains')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>')]
    public array $grains;

    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\Rollups $rollups
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('rollups')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\Rollups')]
    public Rollups $rollups;

    /**
     * Whether this metric can be requested with a `cohort` specification.
     *
     * @var bool $cohortEligible
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('cohortEligible')]
    public bool $cohortEligible;

    /**
     * `money_minor` means values are returned already divided by 100. Absent for dimensionless numbers.
     *
     * @var ?string $unit
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('unit')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $unit = null;

    /**
     * The declared fact source this metric reads, where it reads one.
     *
     * @var ?string $factSource
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('factSource')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $factSource = null;

    /**
     * Earliest instant this metric's source can be trusted (ISO 8601). A range opened before it returns a confident but incomplete answer.
     *
     * @var ?string $coveredFrom
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('coveredFrom')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $coveredFrom = null;

    /**
     * @param  string  $key
     * @param  string  $kind
     * @param  string  $subject
     * @param  string  $description
     * @param  array<string>  $assumptions
     * @param  string  $measuredOn
     * @param  string  $additivity
     * @param  bool  $currencyConverted
     * @param  string  $sourceModel
     * @param  array<string>  $groupBy
     * @param  \Juo\AdminAPI\Models\Operations\Filter  $filter
     * @param  array<string>  $grains
     * @param  \Juo\AdminAPI\Models\Operations\Rollups  $rollups
     * @param  bool  $cohortEligible
     * @param  ?string  $unit
     * @param  ?string  $factSource
     * @param  ?string  $coveredFrom
     * @phpstan-pure
     */
    public function __construct(string $key, string $kind, string $subject, string $description, array $assumptions, string $measuredOn, string $additivity, bool $currencyConverted, string $sourceModel, array $groupBy, Filter $filter, array $grains, Rollups $rollups, bool $cohortEligible, ?string $unit = null, ?string $factSource = null, ?string $coveredFrom = null)
    {
        $this->key = $key;
        $this->kind = $kind;
        $this->subject = $subject;
        $this->description = $description;
        $this->assumptions = $assumptions;
        $this->measuredOn = $measuredOn;
        $this->additivity = $additivity;
        $this->currencyConverted = $currencyConverted;
        $this->sourceModel = $sourceModel;
        $this->groupBy = $groupBy;
        $this->filter = $filter;
        $this->grains = $grains;
        $this->rollups = $rollups;
        $this->cohortEligible = $cohortEligible;
        $this->unit = $unit;
        $this->factSource = $factSource;
        $this->coveredFrom = $coveredFrom;
    }
}