<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;

use Juo\AdminAPI\Models\Components;
/** GetSchedulesAdjustmentsResponseBody - Default Response */
class GetSchedulesAdjustmentsResponseBody
{
    /**
     *
     * @var GetSchedulesAdjustmentsResource $resource
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('resource')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\GetSchedulesAdjustmentsResource')]
    public GetSchedulesAdjustmentsResource $resource;

    /**
     *
     * @var bool $hasNextPage
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('hasNextPage')]
    public bool $hasNextPage;

    /**
     *
     * @var bool $hasPrevPage
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('hasPrevPage')]
    public bool $hasPrevPage;

    /**
     * $data
     *
     * @var array<Components\ScheduleAdjustment> $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Juo\AdminAPI\Models\Components\ScheduleAdjustment>')]
    public array $data;

    /**
     *
     * @var ?string $endCursor
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('endCursor')]
    public ?string $endCursor;

    /**
     *
     * @var ?string $startCursor
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('startCursor')]
    public ?string $startCursor;

    /**
     * @param  GetSchedulesAdjustmentsResource  $resource
     * @param  bool  $hasNextPage
     * @param  bool  $hasPrevPage
     * @param  array<Components\ScheduleAdjustment>  $data
     * @param  ?string  $endCursor
     * @param  ?string  $startCursor
     * @phpstan-pure
     */
    public function __construct(GetSchedulesAdjustmentsResource $resource, bool $hasNextPage, bool $hasPrevPage, array $data, ?string $endCursor = null, ?string $startCursor = null)
    {
        $this->resource = $resource;
        $this->hasNextPage = $hasNextPage;
        $this->hasPrevPage = $hasPrevPage;
        $this->data = $data;
        $this->endCursor = $endCursor;
        $this->startCursor = $startCursor;
    }
}