<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;

use Juo\AdminAPI\Utils\SpeakeasyMetadata;
class GetSubscriptionsRequest
{
    /**
     * The search query string. See [search query language](/docs/api-reference/admin/introduction#search-query-language) for information how to build the search query. Supported fields are listed [here](/docs/api-reference/admin/subscriptions/resource#search-query-fields).
     *
     * @var ?string $query
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=query')]
    public ?string $query = null;

    /**
     * See [pagination](/docs/api-reference/admin/introduction#pagination) for more details on how to paginate the results.
     *
     * @var ?string $after
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=after')]
    public ?string $after = null;

    /**
     * See [pagination](/docs/api-reference/admin/introduction#pagination) for more details on how to paginate the results.
     *
     * @var ?string $before
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=before')]
    public ?string $before = null;

    /**
     * Specify which related resources to include in the response. Supports 'customer' and 'paymentMethod'.
     *
     * @var ?array<\Juo\AdminAPI\Models\Operations\ExpandCustomer|\Juo\AdminAPI\Models\Operations\GetSubscriptionsExpandPaymentMethod> $expand
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=expand')]
    public ?array $expand = null;

    /**
     * Unique identifier of the tenant in the system (usually a store identifier)
     *
     * @var ?string $tenant
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=X-Tenant-ID')]
    public ?string $tenant = null;

    /**
     * See [pagination](/docs/api-reference/admin/introduction#pagination) for more details on how to paginate the results.
     *
     * @var ?int $limit
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=limit')]
    public ?int $limit = null;

    /**
     * See [sorting](/docs/api-reference/admin/introduction#sorting) for more details on how to sort the results.
     *
     * @var ?string $sort
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=sort')]
    public ?string $sort = null;

    /**
     * Whether to include canceled subscriptions in the results.
     *
     * @var ?bool $includeCanceledItems
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=includeCanceledItems')]
    public ?bool $includeCanceledItems = null;

    /**
     * @param  ?string  $query
     * @param  ?int  $limit
     * @param  ?string  $after
     * @param  ?string  $before
     * @param  ?string  $sort
     * @param  ?array<\Juo\AdminAPI\Models\Operations\ExpandCustomer|\Juo\AdminAPI\Models\Operations\GetSubscriptionsExpandPaymentMethod>  $expand
     * @param  ?bool  $includeCanceledItems
     * @param  ?string  $tenant
     * @phpstan-pure
     */
    public function __construct(?string $query = null, ?string $after = null, ?string $before = null, ?array $expand = null, ?string $tenant = null, ?int $limit = 20, ?string $sort = 'createdAt:asc', ?bool $includeCanceledItems = false)
    {
        $this->query = $query;
        $this->after = $after;
        $this->before = $before;
        $this->expand = $expand;
        $this->tenant = $tenant;
        $this->limit = $limit;
        $this->sort = $sort;
        $this->includeCanceledItems = $includeCanceledItems;
    }
}