<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;

use Juo\AdminAPI\Utils\SpeakeasyMetadata;
class GetSchedulesRequest
{
    /**
     * The customer identifier
     *
     * @var string $customerId
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=customerId')]
    public string $customerId;

    /**
     *
     * @var int $count
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=count')]
    public int $count;

    /**
     * The search query string. See [search query language](/docs/api-reference/admin/introduction#search-query-language) for information how to build the search query. Supported fields are listed [here](/docs/api-reference/admin/schedules/resource#search-query-fields).
     *
     * @var ?string $query
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=query')]
    public ?string $query = null;

    /**
     * Specify which related resources to include in the response. Currently supports 'paymentMethod'.
     *
     * @var ?array<\Juo\AdminAPI\Models\Operations\GetSchedulesExpand> $expand
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=expand')]
    public ?array $expand = null;

    /**
     *
     * @var ?bool $excludeSkipped
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=excludeSkipped')]
    public ?bool $excludeSkipped = null;

    /**
     * Unique identifier of the tenant in the system (usually a store identifier)
     *
     * @var ?string $tenant
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=X-Tenant-ID')]
    public ?string $tenant = null;

    /**
     * @param  string  $customerId
     * @param  int  $count
     * @param  ?string  $query
     * @param  ?array<\Juo\AdminAPI\Models\Operations\GetSchedulesExpand>  $expand
     * @param  ?bool  $excludeSkipped
     * @param  ?string  $tenant
     * @phpstan-pure
     */
    public function __construct(string $customerId, int $count, ?string $query = null, ?array $expand = null, ?bool $excludeSkipped = null, ?string $tenant = null)
    {
        $this->customerId = $customerId;
        $this->count = $count;
        $this->query = $query;
        $this->expand = $expand;
        $this->excludeSkipped = $excludeSkipped;
        $this->tenant = $tenant;
    }
}