<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class GetWorkflowsIdRunsStatsVariant
{
    /**
     *
     * @var string $variantId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('variantId')]
    public string $variantId;

    /**
     *
     * @var string $variantName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('variantName')]
    public string $variantName;

    /**
     *
     * @var float $sampleSize
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sampleSize')]
    public float $sampleSize;

    /**
     *
     * @var float $conversionRate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('conversionRate')]
    public float $conversionRate;

    /**
     * @param  string  $variantId
     * @param  string  $variantName
     * @param  float  $sampleSize
     * @param  float  $conversionRate
     * @phpstan-pure
     */
    public function __construct(string $variantId, string $variantName, float $sampleSize, float $conversionRate)
    {
        $this->variantId = $variantId;
        $this->variantName = $variantName;
        $this->sampleSize = $sampleSize;
        $this->conversionRate = $conversionRate;
    }
}