<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class Image
{
    /**
     * The URL of the product image
     *
     * @var string $url
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('url')]
    public string $url;

    /**
     *
     * @var ?string $altText
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('altText')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $altText = null;

    /**
     * @param  string  $url
     * @param  ?string  $altText
     * @phpstan-pure
     */
    public function __construct(string $url, ?string $altText = null)
    {
        $this->url = $url;
        $this->altText = $altText;
    }
}