<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class InputCode
{
    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\DiscountSourceCode $discountSource
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('discountSource')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\DiscountSourceCode')]
    public DiscountSourceCode $discountSource;

    /**
     * The discount code to apply
     *
     * @var string $discountCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('discountCode')]
    public string $discountCode;

    /**
     * @param  \Juo\AdminAPI\Models\Operations\DiscountSourceCode  $discountSource
     * @param  string  $discountCode
     * @phpstan-pure
     */
    public function __construct(DiscountSourceCode $discountSource, string $discountCode)
    {
        $this->discountSource = $discountSource;
        $this->discountCode = $discountCode;
    }
}