<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class InputLineItem
{
    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\DiscountSourceManual1 $discountSource
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('discountSource')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\DiscountSourceManual1')]
    public DiscountSourceManual1 $discountSource;

    /**
     * Custom discount title/name
     *
     * @var string $discountCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('discountCode')]
    public string $discountCode;

    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\DiscountTypePercentage1|\Juo\AdminAPI\Models\Operations\DiscountTypeFixedAmount $discountType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('discountType')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\DiscountTypePercentage1|\Juo\AdminAPI\Models\Operations\DiscountTypeFixedAmount')]
    public DiscountTypePercentage1|DiscountTypeFixedAmount $discountType;

    /**
     * Discount value (percentage 0-100 or fixed amount in shop currency)
     *
     * @var float $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    public float $value;

    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\TargetTypeLineItem $targetType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('targetType')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\TargetTypeLineItem')]
    public TargetTypeLineItem $targetType;

    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\TargetingAll1|\Juo\AdminAPI\Models\Operations\TargetingProducts $targeting
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('targeting')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\TargetingAll1|\Juo\AdminAPI\Models\Operations\TargetingProducts')]
    public TargetingAll1|TargetingProducts $targeting;

    /**
     * @param  \Juo\AdminAPI\Models\Operations\DiscountSourceManual1  $discountSource
     * @param  string  $discountCode
     * @param  \Juo\AdminAPI\Models\Operations\DiscountTypePercentage1|\Juo\AdminAPI\Models\Operations\DiscountTypeFixedAmount  $discountType
     * @param  float  $value
     * @param  \Juo\AdminAPI\Models\Operations\TargetTypeLineItem  $targetType
     * @param  \Juo\AdminAPI\Models\Operations\TargetingAll1|\Juo\AdminAPI\Models\Operations\TargetingProducts  $targeting
     * @phpstan-pure
     */
    public function __construct(DiscountSourceManual1 $discountSource, string $discountCode, DiscountTypePercentage1|DiscountTypeFixedAmount $discountType, float $value, TargetTypeLineItem $targetType, TargetingAll1|TargetingProducts $targeting)
    {
        $this->discountSource = $discountSource;
        $this->discountCode = $discountCode;
        $this->discountType = $discountType;
        $this->value = $value;
        $this->targetType = $targetType;
        $this->targeting = $targeting;
    }
}