<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


/** MatcherCycle - Match by cycle number */
class MatcherCycle
{
    /**
     *
     * @var TypeCycle $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\TypeCycle')]
    public TypeCycle $type;

    /**
     *
     * @var MatcherInput1 $input
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('input')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\MatcherInput1')]
    public MatcherInput1 $input;

    /**
     * @param  TypeCycle  $type
     * @param  MatcherInput1  $input
     * @phpstan-pure
     */
    public function __construct(TypeCycle $type, MatcherInput1 $input)
    {
        $this->type = $type;
        $this->input = $input;
    }
}