<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class MatcherInput2
{
    /**
     * Target date for the adjustment
     *
     * @var \DateTime $date
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('date')]
    public \DateTime $date;

    /**
     * @param  \DateTime  $date
     * @phpstan-pure
     */
    public function __construct(\DateTime $date)
    {
        $this->date = $date;
    }
}