<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class MatcherInput1
{
    /**
     * Target cycle number
     *
     * @var int $cycle
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('cycle')]
    public int $cycle;

    /**
     * @param  int  $cycle
     * @phpstan-pure
     */
    public function __construct(int $cycle)
    {
        $this->cycle = $cycle;
    }
}