<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


/** MatcherCycleAndDate - Match by both cycle and date */
class MatcherCycleAndDate
{
    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\TypeCycleAndDate $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\TypeCycleAndDate')]
    public TypeCycleAndDate $type;

    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\MatcherInput3 $input
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('input')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\MatcherInput3')]
    public MatcherInput3 $input;

    /**
     * @param  \Juo\AdminAPI\Models\Operations\TypeCycleAndDate  $type
     * @param  \Juo\AdminAPI\Models\Operations\MatcherInput3  $input
     * @phpstan-pure
     */
    public function __construct(TypeCycleAndDate $type, MatcherInput3 $input)
    {
        $this->type = $type;
        $this->input = $input;
    }
}