<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


enum MetricSubscriptionsCurrentMrr: string
{
    case SubscriptionsCurrentMrr = 'subscriptions:current-mrr';
}
