<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class PatchSubscriptionsSubscriptionIdDiscountsDiscountIdSelectorSome
{
    /**
     *
     * @var PatchSubscriptionsSubscriptionIdDiscountsDiscountIdTypeSome $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PatchSubscriptionsSubscriptionIdDiscountsDiscountIdTypeSome')]
    public PatchSubscriptionsSubscriptionIdDiscountsDiscountIdTypeSome $type;

    /**
     * $lines
     *
     * @var array<string> $lines
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('lines')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>')]
    public array $lines;

    /**
     * @param  PatchSubscriptionsSubscriptionIdDiscountsDiscountIdTypeSome  $type
     * @param  array<string>  $lines
     * @phpstan-pure
     */
    public function __construct(PatchSubscriptionsSubscriptionIdDiscountsDiscountIdTypeSome $type, array $lines)
    {
        $this->type = $type;
        $this->lines = $lines;
    }
}