<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


enum PatchSubscriptionsSubscriptionIdItemsItemIdDeliveryPolicyIntervalYear: string
{
    case Year = 'YEAR';
}
