<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class PatchSubscriptionsSubscriptionIdItemsItemIdDeliveryPolicy
{
    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\PatchSubscriptionsSubscriptionIdItemsItemIdDeliveryPolicyIntervalDay|\Juo\AdminAPI\Models\Operations\PatchSubscriptionsSubscriptionIdItemsItemIdDeliveryPolicyIntervalWeek|\Juo\AdminAPI\Models\Operations\PatchSubscriptionsSubscriptionIdItemsItemIdDeliveryPolicyIntervalMonth|\Juo\AdminAPI\Models\Operations\PatchSubscriptionsSubscriptionIdItemsItemIdDeliveryPolicyIntervalYear $interval
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('interval')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PatchSubscriptionsSubscriptionIdItemsItemIdDeliveryPolicyIntervalDay|\Juo\AdminAPI\Models\Operations\PatchSubscriptionsSubscriptionIdItemsItemIdDeliveryPolicyIntervalWeek|\Juo\AdminAPI\Models\Operations\PatchSubscriptionsSubscriptionIdItemsItemIdDeliveryPolicyIntervalMonth|\Juo\AdminAPI\Models\Operations\PatchSubscriptionsSubscriptionIdItemsItemIdDeliveryPolicyIntervalYear')]
    public PatchSubscriptionsSubscriptionIdItemsItemIdDeliveryPolicyIntervalDay|PatchSubscriptionsSubscriptionIdItemsItemIdDeliveryPolicyIntervalWeek|PatchSubscriptionsSubscriptionIdItemsItemIdDeliveryPolicyIntervalMonth|PatchSubscriptionsSubscriptionIdItemsItemIdDeliveryPolicyIntervalYear $interval;

    /**
     *
     * @var int $intervalCount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('intervalCount')]
    public int $intervalCount;

    /**
     * $anchors
     *
     * @var array<\Juo\AdminAPI\Models\Operations\DeliveryPolicyAnchor> $anchors
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('anchors')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Juo\AdminAPI\Models\Operations\DeliveryPolicyAnchor>')]
    public array $anchors;

    /**
     * @param  \Juo\AdminAPI\Models\Operations\PatchSubscriptionsSubscriptionIdItemsItemIdDeliveryPolicyIntervalDay|\Juo\AdminAPI\Models\Operations\PatchSubscriptionsSubscriptionIdItemsItemIdDeliveryPolicyIntervalWeek|\Juo\AdminAPI\Models\Operations\PatchSubscriptionsSubscriptionIdItemsItemIdDeliveryPolicyIntervalMonth|\Juo\AdminAPI\Models\Operations\PatchSubscriptionsSubscriptionIdItemsItemIdDeliveryPolicyIntervalYear  $interval
     * @param  int  $intervalCount
     * @param  array<\Juo\AdminAPI\Models\Operations\DeliveryPolicyAnchor>  $anchors
     * @phpstan-pure
     */
    public function __construct(PatchSubscriptionsSubscriptionIdItemsItemIdDeliveryPolicyIntervalDay|PatchSubscriptionsSubscriptionIdItemsItemIdDeliveryPolicyIntervalWeek|PatchSubscriptionsSubscriptionIdItemsItemIdDeliveryPolicyIntervalMonth|PatchSubscriptionsSubscriptionIdItemsItemIdDeliveryPolicyIntervalYear $interval, int $intervalCount, array $anchors)
    {
        $this->interval = $interval;
        $this->intervalCount = $intervalCount;
        $this->anchors = $anchors;
    }
}