<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class PatchSubscriptionsSubscriptionIdDiscountsDiscountIdSelectorAll
{
    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\PatchSubscriptionsSubscriptionIdDiscountsDiscountIdTypeAll $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PatchSubscriptionsSubscriptionIdDiscountsDiscountIdTypeAll')]
    public PatchSubscriptionsSubscriptionIdDiscountsDiscountIdTypeAll $type;

    /**
     * @param  \Juo\AdminAPI\Models\Operations\PatchSubscriptionsSubscriptionIdDiscountsDiscountIdTypeAll  $type
     * @phpstan-pure
     */
    public function __construct(PatchSubscriptionsSubscriptionIdDiscountsDiscountIdTypeAll $type)
    {
        $this->type = $type;
    }
}