<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class PatchSubscriptionsSubscriptionIdItemsItemIdRequestBody
{
    /**
     *
     * @var ?int $quantity
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('quantity')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $quantity = null;

    /**
     *
     * @var ?\Juo\AdminAPI\Models\Operations\BillingPolicy $billingPolicy
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('billingPolicy')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\BillingPolicy|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?BillingPolicy $billingPolicy = null;

    /**
     *
     * @var ?\Juo\AdminAPI\Models\Operations\DeliveryPolicy $deliveryPolicy
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('deliveryPolicy')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\DeliveryPolicy|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?DeliveryPolicy $deliveryPolicy = null;

    /**
     * @param  ?int  $quantity
     * @param  ?\Juo\AdminAPI\Models\Operations\BillingPolicy  $billingPolicy
     * @param  ?\Juo\AdminAPI\Models\Operations\DeliveryPolicy  $deliveryPolicy
     * @phpstan-pure
     */
    public function __construct(?int $quantity = null, ?BillingPolicy $billingPolicy = null, ?DeliveryPolicy $deliveryPolicy = null)
    {
        $this->quantity = $quantity;
        $this->billingPolicy = $billingPolicy;
        $this->deliveryPolicy = $deliveryPolicy;
    }
}