<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class PatchSubscriptionsSubscriptionIdItemsItemIdRequestBody
{
    /**
     * Number of units ordered per billing cycle.
     *
     * @var ?int $quantity
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('quantity')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $quantity = null;

    /**
     *
     * @var ?\Juo\AdminAPI\Models\Operations\PatchSubscriptionsSubscriptionIdItemsItemIdBillingPolicy $billingPolicy
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('billingPolicy')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PatchSubscriptionsSubscriptionIdItemsItemIdBillingPolicy|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PatchSubscriptionsSubscriptionIdItemsItemIdBillingPolicy $billingPolicy = null;

    /**
     *
     * @var ?\Juo\AdminAPI\Models\Operations\PatchSubscriptionsSubscriptionIdItemsItemIdDeliveryPolicy $deliveryPolicy
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('deliveryPolicy')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PatchSubscriptionsSubscriptionIdItemsItemIdDeliveryPolicy|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PatchSubscriptionsSubscriptionIdItemsItemIdDeliveryPolicy $deliveryPolicy = null;

    /**
     * @param  ?int  $quantity
     * @param  ?\Juo\AdminAPI\Models\Operations\PatchSubscriptionsSubscriptionIdItemsItemIdBillingPolicy  $billingPolicy
     * @param  ?\Juo\AdminAPI\Models\Operations\PatchSubscriptionsSubscriptionIdItemsItemIdDeliveryPolicy  $deliveryPolicy
     * @phpstan-pure
     */
    public function __construct(?int $quantity = null, ?PatchSubscriptionsSubscriptionIdItemsItemIdBillingPolicy $billingPolicy = null, ?PatchSubscriptionsSubscriptionIdItemsItemIdDeliveryPolicy $deliveryPolicy = null)
    {
        $this->quantity = $quantity;
        $this->billingPolicy = $billingPolicy;
        $this->deliveryPolicy = $deliveryPolicy;
    }
}