<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;

use Juo\AdminAPI\Utils\SpeakeasyMetadata;
class PatchSubscriptionsSubscriptionIdDiscountsDiscountIdRequest
{
    /**
     * The subscription identifier
     *
     * @var string $subscriptionId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=subscriptionId')]
    public string $subscriptionId;

    /**
     * The subscription discount identifier
     *
     * @var string $discountId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=discountId')]
    public string $discountId;

    /**
     * Unique identifier of the tenant in the system (usually a store identifier)
     *
     * @var ?string $tenant
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=X-Tenant-ID')]
    public ?string $tenant = null;

    /**
     *
     * @var ?\Juo\AdminAPI\Models\Operations\PatchSubscriptionsSubscriptionIdDiscountsDiscountIdRequestBody $requestBody
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public ?PatchSubscriptionsSubscriptionIdDiscountsDiscountIdRequestBody $requestBody = null;

    /**
     * @param  string  $subscriptionId
     * @param  string  $discountId
     * @param  ?string  $tenant
     * @param  ?\Juo\AdminAPI\Models\Operations\PatchSubscriptionsSubscriptionIdDiscountsDiscountIdRequestBody  $requestBody
     * @phpstan-pure
     */
    public function __construct(string $subscriptionId, string $discountId, ?string $tenant = null, ?PatchSubscriptionsSubscriptionIdDiscountsDiscountIdRequestBody $requestBody = null)
    {
        $this->subscriptionId = $subscriptionId;
        $this->discountId = $discountId;
        $this->tenant = $tenant;
        $this->requestBody = $requestBody;
    }
}