<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class PatchSubscriptionsSubscriptionIdRequestBody
{
    /**
     * The delivery price for the upcoming renewal.
     *
     * @var ?float $deliveryPrice
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('deliveryPrice')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $deliveryPrice = null;

    /**
     *
     * @var ?string $paymentMethod
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('paymentMethod')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $paymentMethod = null;

    /**
     *
     * @var ?\Juo\AdminAPI\Models\Operations\DeliveryAddress $deliveryAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('deliveryAddress')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\DeliveryAddress|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?DeliveryAddress $deliveryAddress = null;

    /**
     *
     * @var ?\Juo\AdminAPI\Models\Operations\DeliveryMethod $deliveryMethod
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('deliveryMethod')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\DeliveryMethod|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?DeliveryMethod $deliveryMethod = null;

    /**
     *
     * @var ?\DateTime $nextBillingDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('nextBillingDate')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $nextBillingDate = null;

    /**
     * @param  ?float  $deliveryPrice
     * @param  ?string  $paymentMethod
     * @param  ?\Juo\AdminAPI\Models\Operations\DeliveryAddress  $deliveryAddress
     * @param  ?\Juo\AdminAPI\Models\Operations\DeliveryMethod  $deliveryMethod
     * @param  ?\DateTime  $nextBillingDate
     * @phpstan-pure
     */
    public function __construct(?float $deliveryPrice = null, ?string $paymentMethod = null, ?DeliveryAddress $deliveryAddress = null, ?DeliveryMethod $deliveryMethod = null, ?\DateTime $nextBillingDate = null)
    {
        $this->deliveryPrice = $deliveryPrice;
        $this->paymentMethod = $paymentMethod;
        $this->deliveryAddress = $deliveryAddress;
        $this->deliveryMethod = $deliveryMethod;
        $this->nextBillingDate = $nextBillingDate;
    }
}