<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class PaymentMethod2
{
    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\PostSubscriptionsProviderMollie|\Juo\AdminAPI\Models\Operations\PostSubscriptionsProviderStripe|\Juo\AdminAPI\Models\Operations\PostSubscriptionsProviderTpay|\Juo\AdminAPI\Models\Operations\PostSubscriptionsProviderPayu|\Juo\AdminAPI\Models\Operations\PostSubscriptionsProviderPaynl $provider
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('provider')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PostSubscriptionsProviderMollie|\Juo\AdminAPI\Models\Operations\PostSubscriptionsProviderStripe|\Juo\AdminAPI\Models\Operations\PostSubscriptionsProviderTpay|\Juo\AdminAPI\Models\Operations\PostSubscriptionsProviderPayu|\Juo\AdminAPI\Models\Operations\PostSubscriptionsProviderPaynl')]
    public PostSubscriptionsProviderMollie|PostSubscriptionsProviderStripe|PostSubscriptionsProviderTpay|PostSubscriptionsProviderPayu|PostSubscriptionsProviderPaynl $provider;

    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\PostSubscriptionsInstrumentCreditCard|\Juo\AdminAPI\Models\Operations\PostSubscriptionsInstrumentSepaDirectDebit|\Juo\AdminAPI\Models\Operations\PostSubscriptionsInstrumentBlik|\Juo\AdminAPI\Models\Operations\PostSubscriptionsInstrumentBacs $instrument
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('instrument')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PostSubscriptionsInstrumentCreditCard|\Juo\AdminAPI\Models\Operations\PostSubscriptionsInstrumentSepaDirectDebit|\Juo\AdminAPI\Models\Operations\PostSubscriptionsInstrumentBlik|\Juo\AdminAPI\Models\Operations\PostSubscriptionsInstrumentBacs')]
    public PostSubscriptionsInstrumentCreditCard|PostSubscriptionsInstrumentSepaDirectDebit|PostSubscriptionsInstrumentBlik|PostSubscriptionsInstrumentBacs $instrument;

    /**
     *
     * @var ?string $externalId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('externalId')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $externalId = null;

    /**
     *
     * @var ?string $externalCustomerId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('externalCustomerId')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $externalCustomerId = null;

    /**
     * @param  \Juo\AdminAPI\Models\Operations\PostSubscriptionsProviderMollie|\Juo\AdminAPI\Models\Operations\PostSubscriptionsProviderStripe|\Juo\AdminAPI\Models\Operations\PostSubscriptionsProviderTpay|\Juo\AdminAPI\Models\Operations\PostSubscriptionsProviderPayu|\Juo\AdminAPI\Models\Operations\PostSubscriptionsProviderPaynl  $provider
     * @param  \Juo\AdminAPI\Models\Operations\PostSubscriptionsInstrumentCreditCard|\Juo\AdminAPI\Models\Operations\PostSubscriptionsInstrumentSepaDirectDebit|\Juo\AdminAPI\Models\Operations\PostSubscriptionsInstrumentBlik|\Juo\AdminAPI\Models\Operations\PostSubscriptionsInstrumentBacs  $instrument
     * @param  ?string  $externalId
     * @param  ?string  $externalCustomerId
     * @phpstan-pure
     */
    public function __construct(PostSubscriptionsProviderMollie|PostSubscriptionsProviderStripe|PostSubscriptionsProviderTpay|PostSubscriptionsProviderPayu|PostSubscriptionsProviderPaynl $provider, PostSubscriptionsInstrumentCreditCard|PostSubscriptionsInstrumentSepaDirectDebit|PostSubscriptionsInstrumentBlik|PostSubscriptionsInstrumentBacs $instrument, ?string $externalId = null, ?string $externalCustomerId = null)
    {
        $this->provider = $provider;
        $this->instrument = $instrument;
        $this->externalId = $externalId;
        $this->externalCustomerId = $externalCustomerId;
    }
}