<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class PostSubscriptionsSubscriptionIdDiscountsSelectorAll
{
    /**
     *
     * @var PostSubscriptionsSubscriptionIdDiscountsTypeAll $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PostSubscriptionsSubscriptionIdDiscountsTypeAll')]
    public PostSubscriptionsSubscriptionIdDiscountsTypeAll $type;

    /**
     * @param  PostSubscriptionsSubscriptionIdDiscountsTypeAll  $type
     * @phpstan-pure
     */
    public function __construct(PostSubscriptionsSubscriptionIdDiscountsTypeAll $type)
    {
        $this->type = $type;
    }
}