<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class PostWorkflowsTriggerGroup
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\PostWorkflowsLogicTriggerAnd|\Juo\AdminAPI\Models\Operations\PostWorkflowsLogicTriggerOr $logic
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('logic')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PostWorkflowsLogicTriggerAnd|\Juo\AdminAPI\Models\Operations\PostWorkflowsLogicTriggerOr')]
    public PostWorkflowsLogicTriggerAnd|PostWorkflowsLogicTriggerOr $logic;

    /**
     * $items
     *
     * @var array<\Juo\AdminAPI\Models\Operations\PostWorkflowsTriggerItem> $items
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('items')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Juo\AdminAPI\Models\Operations\PostWorkflowsTriggerItem>')]
    public array $items;

    /**
     * @param  string  $id
     * @param  \Juo\AdminAPI\Models\Operations\PostWorkflowsLogicTriggerAnd|\Juo\AdminAPI\Models\Operations\PostWorkflowsLogicTriggerOr  $logic
     * @param  array<\Juo\AdminAPI\Models\Operations\PostWorkflowsTriggerItem>  $items
     * @phpstan-pure
     */
    public function __construct(string $id, PostWorkflowsLogicTriggerAnd|PostWorkflowsLogicTriggerOr $logic, array $items)
    {
        $this->id = $id;
        $this->logic = $logic;
        $this->items = $items;
    }
}