<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


/** PostProductsProductIdVariantsVariantIdPlansResponseBody - Default Response */
class PostProductsProductIdVariantsVariantIdPlansResponseBody
{
    /**
     *
     * @var string $planId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('planId')]
    public string $planId;

    /**
     *
     * @var bool $assigned
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('assigned')]
    public bool $assigned;

    /**
     * @param  string  $planId
     * @param  bool  $assigned
     * @phpstan-pure
     */
    public function __construct(string $planId, bool $assigned = true)
    {
        $this->planId = $planId;
        $this->assigned = $assigned;
    }
}