<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class PostCustomersCustomerIdPaymentMethodsInstrumentBacs
{
    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\PostCustomersCustomerIdPaymentMethodsTypeBacs $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PostCustomersCustomerIdPaymentMethodsTypeBacs')]
    public PostCustomersCustomerIdPaymentMethodsTypeBacs $type;

    /**
     *
     * @var string $lastDigits
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('lastDigits')]
    public string $lastDigits;

    /**
     * @param  \Juo\AdminAPI\Models\Operations\PostCustomersCustomerIdPaymentMethodsTypeBacs  $type
     * @param  string  $lastDigits
     * @phpstan-pure
     */
    public function __construct(PostCustomersCustomerIdPaymentMethodsTypeBacs $type, string $lastDigits)
    {
        $this->type = $type;
        $this->lastDigits = $lastDigits;
    }
}