<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class PostWorkflowsTransitionItem1
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionLeft1 $left
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('left')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionLeft1')]
    public PostWorkflowsTransitionLeft1 $left;

    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorEquals1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorNotEquals1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorGreaterThan1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorGreaterThanOrEqual1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorLessThan1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorLessThanOrEqual1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorIs1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorIsNot1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorIsOneOf1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorIsNotOneOf1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorContains1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorDoesNotContain1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorIsBefore1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorIsAfter1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorIsOn1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorIsOnOrBefore1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorIsOnOrAfter1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorIsEmpty1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorIsNotEmpty1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorContainsWhere1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorDoesNotContainWhere1 $operator
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('operator')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorEquals1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorNotEquals1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorGreaterThan1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorGreaterThanOrEqual1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorLessThan1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorLessThanOrEqual1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorIs1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorIsNot1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorIsOneOf1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorIsNotOneOf1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorContains1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorDoesNotContain1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorIsBefore1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorIsAfter1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorIsOn1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorIsOnOrBefore1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorIsOnOrAfter1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorIsEmpty1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorIsNotEmpty1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorContainsWhere1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorDoesNotContainWhere1')]
    public PostWorkflowsTransitionOperatorEquals1|PostWorkflowsTransitionOperatorNotEquals1|PostWorkflowsTransitionOperatorGreaterThan1|PostWorkflowsTransitionOperatorGreaterThanOrEqual1|PostWorkflowsTransitionOperatorLessThan1|PostWorkflowsTransitionOperatorLessThanOrEqual1|PostWorkflowsTransitionOperatorIs1|PostWorkflowsTransitionOperatorIsNot1|PostWorkflowsTransitionOperatorIsOneOf1|PostWorkflowsTransitionOperatorIsNotOneOf1|PostWorkflowsTransitionOperatorContains1|PostWorkflowsTransitionOperatorDoesNotContain1|PostWorkflowsTransitionOperatorIsBefore1|PostWorkflowsTransitionOperatorIsAfter1|PostWorkflowsTransitionOperatorIsOn1|PostWorkflowsTransitionOperatorIsOnOrBefore1|PostWorkflowsTransitionOperatorIsOnOrAfter1|PostWorkflowsTransitionOperatorIsEmpty1|PostWorkflowsTransitionOperatorIsNotEmpty1|PostWorkflowsTransitionOperatorContainsWhere1|PostWorkflowsTransitionOperatorDoesNotContainWhere1 $operator;

    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionRight1 $right
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('right')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionRight1')]
    public PostWorkflowsTransitionRight1 $right;

    /**
     * @param  string  $id
     * @param  \Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionLeft1  $left
     * @param  \Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorEquals1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorNotEquals1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorGreaterThan1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorGreaterThanOrEqual1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorLessThan1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorLessThanOrEqual1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorIs1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorIsNot1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorIsOneOf1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorIsNotOneOf1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorContains1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorDoesNotContain1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorIsBefore1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorIsAfter1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorIsOn1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorIsOnOrBefore1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorIsOnOrAfter1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorIsEmpty1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorIsNotEmpty1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorContainsWhere1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionOperatorDoesNotContainWhere1  $operator
     * @param  \Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionRight1  $right
     * @phpstan-pure
     */
    public function __construct(string $id, PostWorkflowsTransitionLeft1 $left, PostWorkflowsTransitionOperatorEquals1|PostWorkflowsTransitionOperatorNotEquals1|PostWorkflowsTransitionOperatorGreaterThan1|PostWorkflowsTransitionOperatorGreaterThanOrEqual1|PostWorkflowsTransitionOperatorLessThan1|PostWorkflowsTransitionOperatorLessThanOrEqual1|PostWorkflowsTransitionOperatorIs1|PostWorkflowsTransitionOperatorIsNot1|PostWorkflowsTransitionOperatorIsOneOf1|PostWorkflowsTransitionOperatorIsNotOneOf1|PostWorkflowsTransitionOperatorContains1|PostWorkflowsTransitionOperatorDoesNotContain1|PostWorkflowsTransitionOperatorIsBefore1|PostWorkflowsTransitionOperatorIsAfter1|PostWorkflowsTransitionOperatorIsOn1|PostWorkflowsTransitionOperatorIsOnOrBefore1|PostWorkflowsTransitionOperatorIsOnOrAfter1|PostWorkflowsTransitionOperatorIsEmpty1|PostWorkflowsTransitionOperatorIsNotEmpty1|PostWorkflowsTransitionOperatorContainsWhere1|PostWorkflowsTransitionOperatorDoesNotContainWhere1 $operator, PostWorkflowsTransitionRight1 $right)
    {
        $this->id = $id;
        $this->left = $left;
        $this->operator = $operator;
        $this->right = $right;
    }
}