<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class PostSubscriptionsInstrumentBlik
{
    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\PaymentMethodTypeBlik $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PaymentMethodTypeBlik')]
    public PaymentMethodTypeBlik $type;

    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\PostSubscriptionsAlias $alias
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('alias')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PostSubscriptionsAlias')]
    public PostSubscriptionsAlias $alias;

    /**
     * @param  \Juo\AdminAPI\Models\Operations\PaymentMethodTypeBlik  $type
     * @param  \Juo\AdminAPI\Models\Operations\PostSubscriptionsAlias  $alias
     * @phpstan-pure
     */
    public function __construct(PaymentMethodTypeBlik $type, PostSubscriptionsAlias $alias)
    {
        $this->type = $type;
        $this->alias = $alias;
    }
}