<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class PostProductsProductIdVariantsRequestBody
{
    /**
     *
     * @var float $price
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('price')]
    public float $price;

    /**
     *
     * @var ?float $compareAtPrice
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('compareAtPrice')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $compareAtPrice = null;

    /**
     *
     * @var ?string $sku
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sku')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $sku = null;

    /**
     *
     * @var ?string $barcode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('barcode')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $barcode = null;

    /**
     * $optionValues
     *
     * @var ?array<\Juo\AdminAPI\Models\Operations\OptionValue> $optionValues
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('optionValues')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Juo\AdminAPI\Models\Operations\OptionValue>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $optionValues = null;

    /**
     * @param  float  $price
     * @param  ?float  $compareAtPrice
     * @param  ?string  $sku
     * @param  ?string  $barcode
     * @param  ?array<\Juo\AdminAPI\Models\Operations\OptionValue>  $optionValues
     * @phpstan-pure
     */
    public function __construct(float $price, ?float $compareAtPrice = null, ?string $sku = null, ?string $barcode = null, ?array $optionValues = null)
    {
        $this->price = $price;
        $this->compareAtPrice = $compareAtPrice;
        $this->sku = $sku;
        $this->barcode = $barcode;
        $this->optionValues = $optionValues;
    }
}