<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class PostWorkflowsTransitionGroup2
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionLogicAnd2|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionLogicOr2 $logic
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('logic')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionLogicAnd2|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionLogicOr2')]
    public PostWorkflowsTransitionLogicAnd2|PostWorkflowsTransitionLogicOr2 $logic;

    /**
     * $items
     *
     * @var array<\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionItem2> $items
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('items')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionItem2>')]
    public array $items;

    /**
     * @param  string  $id
     * @param  \Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionLogicAnd2|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionLogicOr2  $logic
     * @param  array<\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionItem2>  $items
     * @phpstan-pure
     */
    public function __construct(string $id, PostWorkflowsTransitionLogicAnd2|PostWorkflowsTransitionLogicOr2 $logic, array $items)
    {
        $this->id = $id;
        $this->logic = $logic;
        $this->items = $items;
    }
}