<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;

use Juo\AdminAPI\Utils\SpeakeasyMetadata;
class PostCustomersCustomerIdPaymentMethodsRequest
{
    /**
     * The customer identifier
     *
     * @var string $customerId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=customerId')]
    public string $customerId;

    /**
     * Unique identifier of the tenant in the system (usually a store identifier)
     *
     * @var ?string $tenant
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=X-Tenant-ID')]
    public ?string $tenant = null;

    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\Bogus|\Juo\AdminAPI\Models\Operations\PostCustomersCustomerIdPaymentMethodsRequestBody|null $requestBody
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Bogus|PostCustomersCustomerIdPaymentMethodsRequestBody|null $requestBody = null;

    /**
     * @param  string  $customerId
     * @param  ?string  $tenant
     * @param  \Juo\AdminAPI\Models\Operations\Bogus|\Juo\AdminAPI\Models\Operations\PostCustomersCustomerIdPaymentMethodsRequestBody|null  $requestBody
     * @phpstan-pure
     */
    public function __construct(string $customerId, ?string $tenant = null, Bogus|PostCustomersCustomerIdPaymentMethodsRequestBody|null $requestBody = null)
    {
        $this->customerId = $customerId;
        $this->tenant = $tenant;
        $this->requestBody = $requestBody;
    }
}