<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


/** PostSchedulesAdjustmentsInterval - Override billing interval for this cycle */
class PostSchedulesAdjustmentsInterval
{
    /**
     * Number of intervals
     *
     * @var int $intervalCount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('intervalCount')]
    public int $intervalCount;

    /**
     * Interval unit
     *
     * @var PostSchedulesAdjustmentsIntervalDay|PostSchedulesAdjustmentsIntervalWeek|PostSchedulesAdjustmentsIntervalMonth|PostSchedulesAdjustmentsIntervalYear $interval
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('interval')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PostSchedulesAdjustmentsIntervalDay|\Juo\AdminAPI\Models\Operations\PostSchedulesAdjustmentsIntervalWeek|\Juo\AdminAPI\Models\Operations\PostSchedulesAdjustmentsIntervalMonth|\Juo\AdminAPI\Models\Operations\PostSchedulesAdjustmentsIntervalYear')]
    public PostSchedulesAdjustmentsIntervalDay|PostSchedulesAdjustmentsIntervalWeek|PostSchedulesAdjustmentsIntervalMonth|PostSchedulesAdjustmentsIntervalYear $interval;

    /**
     * @param  int  $intervalCount
     * @param  PostSchedulesAdjustmentsIntervalDay|PostSchedulesAdjustmentsIntervalWeek|PostSchedulesAdjustmentsIntervalMonth|PostSchedulesAdjustmentsIntervalYear  $interval
     * @phpstan-pure
     */
    public function __construct(int $intervalCount, PostSchedulesAdjustmentsIntervalDay|PostSchedulesAdjustmentsIntervalWeek|PostSchedulesAdjustmentsIntervalMonth|PostSchedulesAdjustmentsIntervalYear $interval)
    {
        $this->intervalCount = $intervalCount;
        $this->interval = $interval;
    }
}