<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class PostWorkflowsTransitionConditions1
{
    /**
     * $groups
     *
     * @var array<\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionGroup1> $groups
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('groups')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionGroup1>')]
    public array $groups;

    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionRootLogicAnd1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionRootLogicOr1 $rootLogic
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('rootLogic')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionRootLogicAnd1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionRootLogicOr1')]
    public PostWorkflowsTransitionRootLogicAnd1|PostWorkflowsTransitionRootLogicOr1 $rootLogic;

    /**
     * @param  array<\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionGroup1>  $groups
     * @param  \Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionRootLogicAnd1|\Juo\AdminAPI\Models\Operations\PostWorkflowsTransitionRootLogicOr1  $rootLogic
     * @phpstan-pure
     */
    public function __construct(array $groups, PostWorkflowsTransitionRootLogicAnd1|PostWorkflowsTransitionRootLogicOr1 $rootLogic)
    {
        $this->groups = $groups;
        $this->rootLogic = $rootLogic;
    }
}