<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class PostSubscriptionsInstrumentSepaDirectDebit
{
    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\PaymentMethodTypeSepaDirectDebit $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PaymentMethodTypeSepaDirectDebit')]
    public PaymentMethodTypeSepaDirectDebit $type;

    /**
     *
     * @var string $consumerName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('consumerName')]
    public string $consumerName;

    /**
     *
     * @var string $consumerAccount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('consumerAccount')]
    public string $consumerAccount;

    /**
     *
     * @var string $consumerBic
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('consumerBic')]
    public string $consumerBic;

    /**
     *
     * @var \DateTime $signedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('signedAt')]
    public \DateTime $signedAt;

    /**
     *
     * @var ?string $externalMandateId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('externalMandateId')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $externalMandateId = null;

    /**
     * @param  \Juo\AdminAPI\Models\Operations\PaymentMethodTypeSepaDirectDebit  $type
     * @param  string  $consumerName
     * @param  string  $consumerAccount
     * @param  string  $consumerBic
     * @param  \DateTime  $signedAt
     * @param  ?string  $externalMandateId
     * @phpstan-pure
     */
    public function __construct(PaymentMethodTypeSepaDirectDebit $type, string $consumerName, string $consumerAccount, string $consumerBic, \DateTime $signedAt, ?string $externalMandateId = null)
    {
        $this->type = $type;
        $this->consumerName = $consumerName;
        $this->consumerAccount = $consumerAccount;
        $this->consumerBic = $consumerBic;
        $this->signedAt = $signedAt;
        $this->externalMandateId = $externalMandateId;
    }
}