<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class PostProductsRequestBody
{
    /**
     *
     * @var string $title
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('title')]
    public string $title;

    /**
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $description = null;

    /**
     *
     * @var ?string $vendor
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('vendor')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $vendor = null;

    /**
     *
     * @var ?string $productType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('productType')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $productType = null;

    /**
     * $tags
     *
     * @var ?array<string> $tags
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tags')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $tags = null;

    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\PostProductsStatusActive|\Juo\AdminAPI\Models\Operations\PostProductsStatusDraft|null $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PostProductsStatusActive|\Juo\AdminAPI\Models\Operations\PostProductsStatusDraft|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public PostProductsStatusActive|PostProductsStatusDraft|null $status = null;

    /**
     * The product taxonomy category identifier.
     *
     * @var ?string $category
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('category')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $category = null;

    /**
     * Collection IDs to associate the product with
     *
     * @var ?array<string> $collections
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('collections')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $collections = null;

    /**
     *
     * @var ?\Juo\AdminAPI\Models\Operations\Image $image
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('image')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\Image|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Image $image = null;

    /**
     * @param  string  $title
     * @param  ?string  $description
     * @param  ?string  $vendor
     * @param  ?string  $productType
     * @param  ?array<string>  $tags
     * @param  \Juo\AdminAPI\Models\Operations\PostProductsStatusActive|\Juo\AdminAPI\Models\Operations\PostProductsStatusDraft|null  $status
     * @param  ?string  $category
     * @param  ?array<string>  $collections
     * @param  ?\Juo\AdminAPI\Models\Operations\Image  $image
     * @phpstan-pure
     */
    public function __construct(string $title, ?string $description = null, ?string $vendor = null, ?string $productType = null, ?array $tags = null, PostProductsStatusActive|PostProductsStatusDraft|null $status = null, ?string $category = null, ?array $collections = null, ?Image $image = null)
    {
        $this->title = $title;
        $this->description = $description;
        $this->vendor = $vendor;
        $this->productType = $productType;
        $this->tags = $tags;
        $this->status = $status;
        $this->category = $category;
        $this->collections = $collections;
        $this->image = $image;
    }
}