<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class PostSubscriptionsRequestBody
{
    /**
     *
     * @var string $customerId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('customerId')]
    public string $customerId;

    /**
     *
     * @var \DateTime $nextBillingDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('nextBillingDate')]
    public \DateTime $nextBillingDate;

    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\PostSubscriptionsBillingPolicy $billingPolicy
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('billingPolicy')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PostSubscriptionsBillingPolicy')]
    public PostSubscriptionsBillingPolicy $billingPolicy;

    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\PaymentMethod1|\Juo\AdminAPI\Models\Operations\PaymentMethod2 $paymentMethod
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('paymentMethod')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PaymentMethod1|\Juo\AdminAPI\Models\Operations\PaymentMethod2')]
    public PaymentMethod1|PaymentMethod2 $paymentMethod;

    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\PostSubscriptionsDeliveryAddress $deliveryAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('deliveryAddress')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PostSubscriptionsDeliveryAddress')]
    public PostSubscriptionsDeliveryAddress $deliveryAddress;

    /**
     * $items
     *
     * @var array<\Juo\AdminAPI\Models\Operations\PostSubscriptionsItem> $items
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('items')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Juo\AdminAPI\Models\Operations\PostSubscriptionsItem>')]
    public array $items;

    /**
     *
     * @var ?\Juo\AdminAPI\Models\Operations\PostSubscriptionsDeliveryPolicy $deliveryPolicy
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('deliveryPolicy')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PostSubscriptionsDeliveryPolicy|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PostSubscriptionsDeliveryPolicy $deliveryPolicy = null;

    /**
     * The subscription's initial lifecycle status. Defaults to `active` if not provided. Any status except `merged` may be set, e.g. when migrating subscriptions from another platform. Creating a subscription in `canceled`, `failed`, or `expired` sets its cancellation date and skips customer notifications.
     *
     * @var ?\Juo\AdminAPI\Models\Operations\PostSubscriptionsStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PostSubscriptionsStatus|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PostSubscriptionsStatus $status = null;

    /**
     * ISO 4217 currency code to create the subscription in. Defaults to the shop's currency if not provided. Must be one of the shop's enabled presentment currencies.
     *
     * @var ?\Juo\AdminAPI\Models\Operations\CurrencyCode $currencyCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currencyCode')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\CurrencyCode|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CurrencyCode $currencyCode = null;

    /**
     * The delivery price for the subscription. Defaults to 0.00 if not provided.
     *
     * @var ?float $deliveryPrice
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('deliveryPrice')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $deliveryPrice = null;

    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\PostSubscriptionsDeliveryMethodShipping|\Juo\AdminAPI\Models\Operations\DeliveryMethodLocalDelivery|\Juo\AdminAPI\Models\Operations\DeliveryMethodPickup|null $deliveryMethod
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('deliveryMethod')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PostSubscriptionsDeliveryMethodShipping|\Juo\AdminAPI\Models\Operations\DeliveryMethodLocalDelivery|\Juo\AdminAPI\Models\Operations\DeliveryMethodPickup|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public PostSubscriptionsDeliveryMethodShipping|DeliveryMethodLocalDelivery|DeliveryMethodPickup|null $deliveryMethod = null;

    /**
     * @param  string  $customerId
     * @param  \DateTime  $nextBillingDate
     * @param  \Juo\AdminAPI\Models\Operations\PostSubscriptionsBillingPolicy  $billingPolicy
     * @param  \Juo\AdminAPI\Models\Operations\PaymentMethod1|\Juo\AdminAPI\Models\Operations\PaymentMethod2  $paymentMethod
     * @param  \Juo\AdminAPI\Models\Operations\PostSubscriptionsDeliveryAddress  $deliveryAddress
     * @param  array<\Juo\AdminAPI\Models\Operations\PostSubscriptionsItem>  $items
     * @param  ?\Juo\AdminAPI\Models\Operations\PostSubscriptionsDeliveryPolicy  $deliveryPolicy
     * @param  ?\Juo\AdminAPI\Models\Operations\PostSubscriptionsStatus  $status
     * @param  ?\Juo\AdminAPI\Models\Operations\CurrencyCode  $currencyCode
     * @param  ?float  $deliveryPrice
     * @param  \Juo\AdminAPI\Models\Operations\PostSubscriptionsDeliveryMethodShipping|\Juo\AdminAPI\Models\Operations\DeliveryMethodLocalDelivery|\Juo\AdminAPI\Models\Operations\DeliveryMethodPickup|null  $deliveryMethod
     * @phpstan-pure
     */
    public function __construct(string $customerId, \DateTime $nextBillingDate, PostSubscriptionsBillingPolicy $billingPolicy, PaymentMethod1|PaymentMethod2 $paymentMethod, PostSubscriptionsDeliveryAddress $deliveryAddress, array $items, ?PostSubscriptionsDeliveryPolicy $deliveryPolicy = null, ?PostSubscriptionsStatus $status = null, ?CurrencyCode $currencyCode = null, ?float $deliveryPrice = null, PostSubscriptionsDeliveryMethodShipping|DeliveryMethodLocalDelivery|DeliveryMethodPickup|null $deliveryMethod = null)
    {
        $this->customerId = $customerId;
        $this->nextBillingDate = $nextBillingDate;
        $this->billingPolicy = $billingPolicy;
        $this->paymentMethod = $paymentMethod;
        $this->deliveryAddress = $deliveryAddress;
        $this->items = $items;
        $this->deliveryPolicy = $deliveryPolicy;
        $this->status = $status;
        $this->currencyCode = $currencyCode;
        $this->deliveryPrice = $deliveryPrice;
        $this->deliveryMethod = $deliveryMethod;
    }
}