<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;

use Juo\AdminAPI\Utils\SpeakeasyMetadata;
class PostWorkflowsIdUnpublishRequest
{
    /**
     * The workflow identifier
     *
     * @var string $id
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;

    /**
     * Unique identifier of the tenant in the system (usually a store identifier)
     *
     * @var ?string $tenant
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=X-Tenant-ID')]
    public ?string $tenant = null;

    /**
     * @param  string  $id
     * @param  ?string  $tenant
     * @phpstan-pure
     */
    public function __construct(string $id, ?string $tenant = null)
    {
        $this->id = $id;
        $this->tenant = $tenant;
    }
}