<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class PostSubscriptionsInstrumentCreditCard
{
    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\PaymentMethodTypeCreditCard $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PaymentMethodTypeCreditCard')]
    public PaymentMethodTypeCreditCard $type;

    /**
     *
     * @var string $brand
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('brand')]
    public string $brand;

    /**
     *
     * @var int $expiryMonth
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('expiryMonth')]
    public int $expiryMonth;

    /**
     *
     * @var int $expiryYear
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('expiryYear')]
    public int $expiryYear;

    /**
     *
     * @var string $lastDigits
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('lastDigits')]
    public string $lastDigits;

    /**
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     *
     * @var ?string $source
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $source = null;

    /**
     * @param  \Juo\AdminAPI\Models\Operations\PaymentMethodTypeCreditCard  $type
     * @param  string  $brand
     * @param  int  $expiryMonth
     * @param  int  $expiryYear
     * @param  string  $lastDigits
     * @param  string  $name
     * @param  ?string  $source
     * @phpstan-pure
     */
    public function __construct(PaymentMethodTypeCreditCard $type, string $brand, int $expiryMonth, int $expiryYear, string $lastDigits, string $name, ?string $source = null)
    {
        $this->type = $type;
        $this->brand = $brand;
        $this->expiryMonth = $expiryMonth;
        $this->expiryYear = $expiryYear;
        $this->lastDigits = $lastDigits;
        $this->name = $name;
        $this->source = $source;
    }
}