<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


/** PostAnalyticsQueryResponseBody - Default Response */
class PostAnalyticsQueryResponseBody
{
    /**
     * Ordered list of time-bucketed data points.
     *
     * @var array<\Juo\AdminAPI\Models\Operations\Series> $series
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('series')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Juo\AdminAPI\Models\Operations\Series>')]
    public array $series;

    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\Meta $meta
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('meta')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\Meta')]
    public Meta $meta;

    /**
     * @param  array<\Juo\AdminAPI\Models\Operations\Series>  $series
     * @param  \Juo\AdminAPI\Models\Operations\Meta  $meta
     * @phpstan-pure
     */
    public function __construct(array $series, Meta $meta)
    {
        $this->series = $series;
        $this->meta = $meta;
    }
}