<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


enum PostWorkflowsTransitionOperatorIsNot1: string
{
    case IsNot = 'is_not';
}
