<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;

use Juo\AdminAPI\Utils\SpeakeasyMetadata;
class PostProductsProductIdVariantsVariantIdPlansRequest
{
    /**
     * The product identifier
     *
     * @var string $productId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=productId')]
    public string $productId;

    /**
     * The variant identifier
     *
     * @var string $variantId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=variantId')]
    public string $variantId;

    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\PostProductsProductIdVariantsVariantIdPlansRequestBody $requestBody
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public PostProductsProductIdVariantsVariantIdPlansRequestBody $requestBody;

    /**
     * Unique identifier of the tenant in the system (usually a store identifier)
     *
     * @var ?string $tenant
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=X-Tenant-ID')]
    public ?string $tenant = null;

    /**
     * @param  string  $productId
     * @param  string  $variantId
     * @param  \Juo\AdminAPI\Models\Operations\PostProductsProductIdVariantsVariantIdPlansRequestBody  $requestBody
     * @param  ?string  $tenant
     * @phpstan-pure
     */
    public function __construct(string $productId, string $variantId, PostProductsProductIdVariantsVariantIdPlansRequestBody $requestBody, ?string $tenant = null)
    {
        $this->productId = $productId;
        $this->variantId = $variantId;
        $this->requestBody = $requestBody;
        $this->tenant = $tenant;
    }
}