<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


enum PostWorkflowsTransitionOperatorDoesNotContain2: string
{
    case DoesNotContain = 'does_not_contain';
}
