<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


enum PostWorkflowsOperatorTriggerLessThan: string
{
    case LessThan = 'less_than';
}
