<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


enum PostWorkflowsTransitionOperatorIsNotEmpty2: string
{
    case IsNotEmpty = 'is_not_empty';
}
