<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class PostSubscriptionsSubscriptionIdItemsRequestBody
{
    /**
     *
     * @var string $variant
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('variant')]
    public string $variant;

    /**
     *
     * @var int $quantity
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('quantity')]
    public int $quantity;

    /**
     * Set a custom base price for the variant that will be used before subscription discounts are applied. If not specified, the variant's regular price will be used.
     *
     * @var ?float $price
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('price')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $price = null;

    /**
     * The number of billing cycles for which this item will be applied. After the recurring cycle limit is met the item will be removed from the subscription.
     *
     * @var ?int $recurringCycleLimit
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('recurringCycleLimit')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $recurringCycleLimit = null;

    /**
     * @param  string  $variant
     * @param  int  $quantity
     * @param  ?float  $price
     * @param  ?int  $recurringCycleLimit
     * @phpstan-pure
     */
    public function __construct(string $variant, int $quantity, ?float $price = null, ?int $recurringCycleLimit = null)
    {
        $this->variant = $variant;
        $this->quantity = $quantity;
        $this->price = $price;
        $this->recurringCycleLimit = $recurringCycleLimit;
    }
}