<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class PostWorkflowsTrigger
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var string $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    public string $type;

    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\PostWorkflowsCategorySystemEvent|\Juo\AdminAPI\Models\Operations\PostWorkflowsCategoryCustomerInitiated|\Juo\AdminAPI\Models\Operations\PostWorkflowsCategoryAdminInitiated|\Juo\AdminAPI\Models\Operations\PostWorkflowsCategoryTimeBased $category
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('category')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PostWorkflowsCategorySystemEvent|\Juo\AdminAPI\Models\Operations\PostWorkflowsCategoryCustomerInitiated|\Juo\AdminAPI\Models\Operations\PostWorkflowsCategoryAdminInitiated|\Juo\AdminAPI\Models\Operations\PostWorkflowsCategoryTimeBased')]
    public PostWorkflowsCategorySystemEvent|PostWorkflowsCategoryCustomerInitiated|PostWorkflowsCategoryAdminInitiated|PostWorkflowsCategoryTimeBased $category;

    /**
     *
     * @var ?\Juo\AdminAPI\Models\Operations\PostWorkflowsTriggerConditions $conditions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('conditions')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PostWorkflowsTriggerConditions|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PostWorkflowsTriggerConditions $conditions = null;

    /**
     * @param  string  $id
     * @param  string  $type
     * @param  \Juo\AdminAPI\Models\Operations\PostWorkflowsCategorySystemEvent|\Juo\AdminAPI\Models\Operations\PostWorkflowsCategoryCustomerInitiated|\Juo\AdminAPI\Models\Operations\PostWorkflowsCategoryAdminInitiated|\Juo\AdminAPI\Models\Operations\PostWorkflowsCategoryTimeBased  $category
     * @param  ?\Juo\AdminAPI\Models\Operations\PostWorkflowsTriggerConditions  $conditions
     * @phpstan-pure
     */
    public function __construct(string $id, string $type, PostWorkflowsCategorySystemEvent|PostWorkflowsCategoryCustomerInitiated|PostWorkflowsCategoryAdminInitiated|PostWorkflowsCategoryTimeBased $category, ?PostWorkflowsTriggerConditions $conditions = null)
    {
        $this->id = $id;
        $this->type = $type;
        $this->category = $category;
        $this->conditions = $conditions;
    }
}