<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;

use Juo\AdminAPI\Utils\SpeakeasyMetadata;
class PostSubscriptionsSubscriptionIdCancelRequest
{
    /**
     * The subscription identifier
     *
     * @var string $subscriptionId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=subscriptionId')]
    public string $subscriptionId;

    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\PostSubscriptionsSubscriptionIdCancelRequestBody $requestBody
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public PostSubscriptionsSubscriptionIdCancelRequestBody $requestBody;

    /**
     * Unique identifier of the tenant in the system (usually a store identifier)
     *
     * @var ?string $tenant
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=X-Tenant-ID')]
    public ?string $tenant = null;

    /**
     * @param  string  $subscriptionId
     * @param  \Juo\AdminAPI\Models\Operations\PostSubscriptionsSubscriptionIdCancelRequestBody  $requestBody
     * @param  ?string  $tenant
     * @phpstan-pure
     */
    public function __construct(string $subscriptionId, PostSubscriptionsSubscriptionIdCancelRequestBody $requestBody, ?string $tenant = null)
    {
        $this->subscriptionId = $subscriptionId;
        $this->requestBody = $requestBody;
        $this->tenant = $tenant;
    }
}