<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


enum PostWorkflowsTransitionOperatorNotEquals1: string
{
    case NotEquals = 'not_equals';
}
