<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;

use Juo\AdminAPI\Utils\SpeakeasyMetadata;
class PostSchedulesAdjustmentsRequest
{
    /**
     *
     * @var PostSchedulesAdjustmentsRequestBody $requestBody
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public PostSchedulesAdjustmentsRequestBody $requestBody;

    /**
     * Unique identifier of the tenant in the system (usually a store identifier)
     *
     * @var ?string $tenant
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=X-Tenant-ID')]
    public ?string $tenant = null;

    /**
     * @param  PostSchedulesAdjustmentsRequestBody  $requestBody
     * @param  ?string  $tenant
     * @phpstan-pure
     */
    public function __construct(PostSchedulesAdjustmentsRequestBody $requestBody, ?string $tenant = null)
    {
        $this->requestBody = $requestBody;
        $this->tenant = $tenant;
    }
}