<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


enum PostWorkflowsOperatorTriggerIsNotOneOf: string
{
    case IsNotOneOf = 'is_not_one_of';
}
