<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class PostSubscriptionsSubscriptionIdDiscountsTargetShipping
{
    /**
     *
     * @var PostSubscriptionsSubscriptionIdDiscountsTypeShipping $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PostSubscriptionsSubscriptionIdDiscountsTypeShipping')]
    public PostSubscriptionsSubscriptionIdDiscountsTypeShipping $type;

    /**
     * @param  PostSubscriptionsSubscriptionIdDiscountsTypeShipping  $type
     * @phpstan-pure
     */
    public function __construct(PostSubscriptionsSubscriptionIdDiscountsTypeShipping $type)
    {
        $this->type = $type;
    }
}