<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class PostCustomersCustomerIdPaymentMethodsRequestBody
{
    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\PostCustomersCustomerIdPaymentMethodsProviderMollie|\Juo\AdminAPI\Models\Operations\PostCustomersCustomerIdPaymentMethodsProviderStripe|\Juo\AdminAPI\Models\Operations\PostCustomersCustomerIdPaymentMethodsProviderTpay|\Juo\AdminAPI\Models\Operations\PostCustomersCustomerIdPaymentMethodsProviderPayu|\Juo\AdminAPI\Models\Operations\PostCustomersCustomerIdPaymentMethodsProviderPaynl $provider
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('provider')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PostCustomersCustomerIdPaymentMethodsProviderMollie|\Juo\AdminAPI\Models\Operations\PostCustomersCustomerIdPaymentMethodsProviderStripe|\Juo\AdminAPI\Models\Operations\PostCustomersCustomerIdPaymentMethodsProviderTpay|\Juo\AdminAPI\Models\Operations\PostCustomersCustomerIdPaymentMethodsProviderPayu|\Juo\AdminAPI\Models\Operations\PostCustomersCustomerIdPaymentMethodsProviderPaynl')]
    public PostCustomersCustomerIdPaymentMethodsProviderMollie|PostCustomersCustomerIdPaymentMethodsProviderStripe|PostCustomersCustomerIdPaymentMethodsProviderTpay|PostCustomersCustomerIdPaymentMethodsProviderPayu|PostCustomersCustomerIdPaymentMethodsProviderPaynl $provider;

    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\PostCustomersCustomerIdPaymentMethodsInstrumentCreditCard|\Juo\AdminAPI\Models\Operations\PostCustomersCustomerIdPaymentMethodsInstrumentSepaDirectDebit|\Juo\AdminAPI\Models\Operations\PostCustomersCustomerIdPaymentMethodsInstrumentBlik|\Juo\AdminAPI\Models\Operations\PostCustomersCustomerIdPaymentMethodsInstrumentBacs $instrument
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('instrument')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PostCustomersCustomerIdPaymentMethodsInstrumentCreditCard|\Juo\AdminAPI\Models\Operations\PostCustomersCustomerIdPaymentMethodsInstrumentSepaDirectDebit|\Juo\AdminAPI\Models\Operations\PostCustomersCustomerIdPaymentMethodsInstrumentBlik|\Juo\AdminAPI\Models\Operations\PostCustomersCustomerIdPaymentMethodsInstrumentBacs')]
    public PostCustomersCustomerIdPaymentMethodsInstrumentCreditCard|PostCustomersCustomerIdPaymentMethodsInstrumentSepaDirectDebit|PostCustomersCustomerIdPaymentMethodsInstrumentBlik|PostCustomersCustomerIdPaymentMethodsInstrumentBacs $instrument;

    /**
     *
     * @var ?string $externalId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('externalId')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $externalId = null;

    /**
     *
     * @var ?string $externalCustomerId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('externalCustomerId')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $externalCustomerId = null;

    /**
     * @param  \Juo\AdminAPI\Models\Operations\PostCustomersCustomerIdPaymentMethodsProviderMollie|\Juo\AdminAPI\Models\Operations\PostCustomersCustomerIdPaymentMethodsProviderStripe|\Juo\AdminAPI\Models\Operations\PostCustomersCustomerIdPaymentMethodsProviderTpay|\Juo\AdminAPI\Models\Operations\PostCustomersCustomerIdPaymentMethodsProviderPayu|\Juo\AdminAPI\Models\Operations\PostCustomersCustomerIdPaymentMethodsProviderPaynl  $provider
     * @param  \Juo\AdminAPI\Models\Operations\PostCustomersCustomerIdPaymentMethodsInstrumentCreditCard|\Juo\AdminAPI\Models\Operations\PostCustomersCustomerIdPaymentMethodsInstrumentSepaDirectDebit|\Juo\AdminAPI\Models\Operations\PostCustomersCustomerIdPaymentMethodsInstrumentBlik|\Juo\AdminAPI\Models\Operations\PostCustomersCustomerIdPaymentMethodsInstrumentBacs  $instrument
     * @param  ?string  $externalId
     * @param  ?string  $externalCustomerId
     * @phpstan-pure
     */
    public function __construct(PostCustomersCustomerIdPaymentMethodsProviderMollie|PostCustomersCustomerIdPaymentMethodsProviderStripe|PostCustomersCustomerIdPaymentMethodsProviderTpay|PostCustomersCustomerIdPaymentMethodsProviderPayu|PostCustomersCustomerIdPaymentMethodsProviderPaynl $provider, PostCustomersCustomerIdPaymentMethodsInstrumentCreditCard|PostCustomersCustomerIdPaymentMethodsInstrumentSepaDirectDebit|PostCustomersCustomerIdPaymentMethodsInstrumentBlik|PostCustomersCustomerIdPaymentMethodsInstrumentBacs $instrument, ?string $externalId = null, ?string $externalCustomerId = null)
    {
        $this->provider = $provider;
        $this->instrument = $instrument;
        $this->externalId = $externalId;
        $this->externalCustomerId = $externalCustomerId;
    }
}