<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;

use Juo\AdminAPI\Utils\SpeakeasyMetadata;
class PostCustomersRequest
{
    /**
     * Unique identifier of the tenant in the system (usually a store identifier)
     *
     * @var ?string $tenant
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=X-Tenant-ID')]
    public ?string $tenant = null;

    /**
     *
     * @var ?\Juo\AdminAPI\Models\Operations\PostCustomersRequestBody $requestBody
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public ?PostCustomersRequestBody $requestBody = null;

    /**
     * @param  ?string  $tenant
     * @param  ?\Juo\AdminAPI\Models\Operations\PostCustomersRequestBody  $requestBody
     * @phpstan-pure
     */
    public function __construct(?string $tenant = null, ?PostCustomersRequestBody $requestBody = null)
    {
        $this->tenant = $tenant;
        $this->requestBody = $requestBody;
    }
}