<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class PostSubscriptionsDeliveryMethodShipping
{
    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\DeliveryMethodTypeShipping $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\DeliveryMethodTypeShipping')]
    public DeliveryMethodTypeShipping $type;

    /**
     *
     * @var ?string $title
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('title')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $title = null;

    /**
     * @param  \Juo\AdminAPI\Models\Operations\DeliveryMethodTypeShipping  $type
     * @param  ?string  $title
     * @phpstan-pure
     */
    public function __construct(DeliveryMethodTypeShipping $type, ?string $title = null)
    {
        $this->type = $type;
        $this->title = $title;
    }
}