<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;

use Juo\AdminAPI\Utils\SpeakeasyMetadata;
class PostWorkflowsIdExperimentStepIdConcludeRequest
{
    /**
     * The workflow identifier
     *
     * @var string $id
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;

    /**
     * The experiment step identifier
     *
     * @var string $stepId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=stepId')]
    public string $stepId;

    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\PostWorkflowsIdExperimentStepIdConcludeRequestBody $requestBody
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public PostWorkflowsIdExperimentStepIdConcludeRequestBody $requestBody;

    /**
     * Unique identifier of the tenant in the system (usually a store identifier)
     *
     * @var ?string $tenant
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=X-Tenant-ID')]
    public ?string $tenant = null;

    /**
     * @param  string  $id
     * @param  string  $stepId
     * @param  \Juo\AdminAPI\Models\Operations\PostWorkflowsIdExperimentStepIdConcludeRequestBody  $requestBody
     * @param  ?string  $tenant
     * @phpstan-pure
     */
    public function __construct(string $id, string $stepId, PostWorkflowsIdExperimentStepIdConcludeRequestBody $requestBody, ?string $tenant = null)
    {
        $this->id = $id;
        $this->stepId = $stepId;
        $this->requestBody = $requestBody;
        $this->tenant = $tenant;
    }
}