<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class PostSubscriptionsSubscriptionIdDiscountsRequestBody1
{
    /**
     * Discount code to apply
     *
     * @var string $code
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('code')]
    public string $code;

    /**
     * @param  string  $code
     * @phpstan-pure
     */
    public function __construct(string $code)
    {
        $this->code = $code;
    }
}