<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class PostWorkflowsTriggerItem
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\PostWorkflowsTriggerLeft $left
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('left')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PostWorkflowsTriggerLeft')]
    public PostWorkflowsTriggerLeft $left;

    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerEquals|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerNotEquals|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerGreaterThan|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerGreaterThanOrEqual|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerLessThan|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerLessThanOrEqual|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerIs|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerIsNot|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerIsOneOf|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerIsNotOneOf|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerContains|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerDoesNotContain|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerIsBefore|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerIsAfter|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerIsOn|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerIsOnOrBefore|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerIsOnOrAfter|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerIsEmpty|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerIsNotEmpty|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerContainsWhere|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerDoesNotContainWhere $operator
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('operator')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerEquals|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerNotEquals|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerGreaterThan|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerGreaterThanOrEqual|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerLessThan|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerLessThanOrEqual|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerIs|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerIsNot|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerIsOneOf|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerIsNotOneOf|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerContains|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerDoesNotContain|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerIsBefore|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerIsAfter|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerIsOn|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerIsOnOrBefore|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerIsOnOrAfter|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerIsEmpty|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerIsNotEmpty|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerContainsWhere|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerDoesNotContainWhere')]
    public PostWorkflowsOperatorTriggerEquals|PostWorkflowsOperatorTriggerNotEquals|PostWorkflowsOperatorTriggerGreaterThan|PostWorkflowsOperatorTriggerGreaterThanOrEqual|PostWorkflowsOperatorTriggerLessThan|PostWorkflowsOperatorTriggerLessThanOrEqual|PostWorkflowsOperatorTriggerIs|PostWorkflowsOperatorTriggerIsNot|PostWorkflowsOperatorTriggerIsOneOf|PostWorkflowsOperatorTriggerIsNotOneOf|PostWorkflowsOperatorTriggerContains|PostWorkflowsOperatorTriggerDoesNotContain|PostWorkflowsOperatorTriggerIsBefore|PostWorkflowsOperatorTriggerIsAfter|PostWorkflowsOperatorTriggerIsOn|PostWorkflowsOperatorTriggerIsOnOrBefore|PostWorkflowsOperatorTriggerIsOnOrAfter|PostWorkflowsOperatorTriggerIsEmpty|PostWorkflowsOperatorTriggerIsNotEmpty|PostWorkflowsOperatorTriggerContainsWhere|PostWorkflowsOperatorTriggerDoesNotContainWhere $operator;

    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\PostWorkflowsTriggerRight $right
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('right')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PostWorkflowsTriggerRight')]
    public PostWorkflowsTriggerRight $right;

    /**
     * @param  string  $id
     * @param  \Juo\AdminAPI\Models\Operations\PostWorkflowsTriggerLeft  $left
     * @param  \Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerEquals|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerNotEquals|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerGreaterThan|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerGreaterThanOrEqual|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerLessThan|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerLessThanOrEqual|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerIs|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerIsNot|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerIsOneOf|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerIsNotOneOf|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerContains|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerDoesNotContain|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerIsBefore|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerIsAfter|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerIsOn|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerIsOnOrBefore|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerIsOnOrAfter|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerIsEmpty|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerIsNotEmpty|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerContainsWhere|\Juo\AdminAPI\Models\Operations\PostWorkflowsOperatorTriggerDoesNotContainWhere  $operator
     * @param  \Juo\AdminAPI\Models\Operations\PostWorkflowsTriggerRight  $right
     * @phpstan-pure
     */
    public function __construct(string $id, PostWorkflowsTriggerLeft $left, PostWorkflowsOperatorTriggerEquals|PostWorkflowsOperatorTriggerNotEquals|PostWorkflowsOperatorTriggerGreaterThan|PostWorkflowsOperatorTriggerGreaterThanOrEqual|PostWorkflowsOperatorTriggerLessThan|PostWorkflowsOperatorTriggerLessThanOrEqual|PostWorkflowsOperatorTriggerIs|PostWorkflowsOperatorTriggerIsNot|PostWorkflowsOperatorTriggerIsOneOf|PostWorkflowsOperatorTriggerIsNotOneOf|PostWorkflowsOperatorTriggerContains|PostWorkflowsOperatorTriggerDoesNotContain|PostWorkflowsOperatorTriggerIsBefore|PostWorkflowsOperatorTriggerIsAfter|PostWorkflowsOperatorTriggerIsOn|PostWorkflowsOperatorTriggerIsOnOrBefore|PostWorkflowsOperatorTriggerIsOnOrAfter|PostWorkflowsOperatorTriggerIsEmpty|PostWorkflowsOperatorTriggerIsNotEmpty|PostWorkflowsOperatorTriggerContainsWhere|PostWorkflowsOperatorTriggerDoesNotContainWhere $operator, PostWorkflowsTriggerRight $right)
    {
        $this->id = $id;
        $this->left = $left;
        $this->operator = $operator;
        $this->right = $right;
    }
}