<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class PutWorkflowsIdTransitionConditions1
{
    /**
     * $groups
     *
     * @var array<\Juo\AdminAPI\Models\Operations\PutWorkflowsIdTransitionGroup1> $groups
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('groups')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Juo\AdminAPI\Models\Operations\PutWorkflowsIdTransitionGroup1>')]
    public array $groups;

    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\PutWorkflowsIdTransitionRootLogicAnd1|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdTransitionRootLogicOr1 $rootLogic
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('rootLogic')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PutWorkflowsIdTransitionRootLogicAnd1|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdTransitionRootLogicOr1')]
    public PutWorkflowsIdTransitionRootLogicAnd1|PutWorkflowsIdTransitionRootLogicOr1 $rootLogic;

    /**
     * @param  array<\Juo\AdminAPI\Models\Operations\PutWorkflowsIdTransitionGroup1>  $groups
     * @param  \Juo\AdminAPI\Models\Operations\PutWorkflowsIdTransitionRootLogicAnd1|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdTransitionRootLogicOr1  $rootLogic
     * @phpstan-pure
     */
    public function __construct(array $groups, PutWorkflowsIdTransitionRootLogicAnd1|PutWorkflowsIdTransitionRootLogicOr1 $rootLogic)
    {
        $this->groups = $groups;
        $this->rootLogic = $rootLogic;
    }
}