<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class PutWorkflowsIdTransitionResponse
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var string $targetStepId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('targetStepId')]
    public string $targetStepId;

    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\PutWorkflowsIdTypeResponse $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PutWorkflowsIdTypeResponse')]
    public PutWorkflowsIdTypeResponse $type;

    /**
     *
     * @var string $responseType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('responseType')]
    public string $responseType;

    /**
     *
     * @var ?\Juo\AdminAPI\Models\Operations\PutWorkflowsIdTransitionConditions2 $conditions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('conditions')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PutWorkflowsIdTransitionConditions2|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PutWorkflowsIdTransitionConditions2 $conditions = null;

    /**
     * @param  string  $id
     * @param  string  $targetStepId
     * @param  \Juo\AdminAPI\Models\Operations\PutWorkflowsIdTypeResponse  $type
     * @param  string  $responseType
     * @param  ?\Juo\AdminAPI\Models\Operations\PutWorkflowsIdTransitionConditions2  $conditions
     * @phpstan-pure
     */
    public function __construct(string $id, string $targetStepId, PutWorkflowsIdTypeResponse $type, string $responseType, ?PutWorkflowsIdTransitionConditions2 $conditions = null)
    {
        $this->id = $id;
        $this->targetStepId = $targetStepId;
        $this->type = $type;
        $this->responseType = $responseType;
        $this->conditions = $conditions;
    }
}