<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class PutWorkflowsIdRequestBody
{
    /**
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $description = null;

    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\PutWorkflowsIdStatusDraft|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdStatusPublished|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdStatusArchived|null $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PutWorkflowsIdStatusDraft|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdStatusPublished|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdStatusArchived|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public PutWorkflowsIdStatusDraft|PutWorkflowsIdStatusPublished|PutWorkflowsIdStatusArchived|null $status = null;

    /**
     *
     * @var ?\Juo\AdminAPI\Models\Operations\PutWorkflowsIdTrigger $trigger
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('trigger')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PutWorkflowsIdTrigger|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PutWorkflowsIdTrigger $trigger = null;

    /**
     * $steps
     *
     * @var ?array<\Juo\AdminAPI\Models\Operations\PutWorkflowsIdStep> $steps
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('steps')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Juo\AdminAPI\Models\Operations\PutWorkflowsIdStep>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $steps = null;

    /**
     * $metadata
     *
     * @var ?array<string, mixed> $metadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $metadata = null;

    /**
     * @param  ?string  $name
     * @param  ?string  $description
     * @param  \Juo\AdminAPI\Models\Operations\PutWorkflowsIdStatusDraft|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdStatusPublished|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdStatusArchived|null  $status
     * @param  ?\Juo\AdminAPI\Models\Operations\PutWorkflowsIdTrigger  $trigger
     * @param  ?array<\Juo\AdminAPI\Models\Operations\PutWorkflowsIdStep>  $steps
     * @param  ?array<string, mixed>  $metadata
     * @phpstan-pure
     */
    public function __construct(?string $name = null, ?string $description = null, PutWorkflowsIdStatusDraft|PutWorkflowsIdStatusPublished|PutWorkflowsIdStatusArchived|null $status = null, ?PutWorkflowsIdTrigger $trigger = null, ?array $steps = null, ?array $metadata = null)
    {
        $this->name = $name;
        $this->description = $description;
        $this->status = $status;
        $this->trigger = $trigger;
        $this->steps = $steps;
        $this->metadata = $metadata;
    }
}