<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class PutWorkflowsIdTransitionConditions2
{
    /**
     * $groups
     *
     * @var array<\Juo\AdminAPI\Models\Operations\PutWorkflowsIdTransitionGroup2> $groups
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('groups')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Juo\AdminAPI\Models\Operations\PutWorkflowsIdTransitionGroup2>')]
    public array $groups;

    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\PutWorkflowsIdTransitionRootLogicAnd2|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdTransitionRootLogicOr2 $rootLogic
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('rootLogic')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PutWorkflowsIdTransitionRootLogicAnd2|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdTransitionRootLogicOr2')]
    public PutWorkflowsIdTransitionRootLogicAnd2|PutWorkflowsIdTransitionRootLogicOr2 $rootLogic;

    /**
     * @param  array<\Juo\AdminAPI\Models\Operations\PutWorkflowsIdTransitionGroup2>  $groups
     * @param  \Juo\AdminAPI\Models\Operations\PutWorkflowsIdTransitionRootLogicAnd2|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdTransitionRootLogicOr2  $rootLogic
     * @phpstan-pure
     */
    public function __construct(array $groups, PutWorkflowsIdTransitionRootLogicAnd2|PutWorkflowsIdTransitionRootLogicOr2 $rootLogic)
    {
        $this->groups = $groups;
        $this->rootLogic = $rootLogic;
    }
}