<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class PutWorkflowsIdTriggerItem
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\PutWorkflowsIdTriggerLeft $left
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('left')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PutWorkflowsIdTriggerLeft')]
    public PutWorkflowsIdTriggerLeft $left;

    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerEquals|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerNotEquals|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerGreaterThan|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerGreaterThanOrEqual|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerLessThan|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerLessThanOrEqual|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerIs|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerIsNot|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerIsOneOf|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerIsNotOneOf|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerContains|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerDoesNotContain|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerIsBefore|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerIsAfter|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerIsOn|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerIsOnOrBefore|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerIsOnOrAfter|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerIsEmpty|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerIsNotEmpty|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerContainsWhere|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerDoesNotContainWhere $operator
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('operator')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerEquals|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerNotEquals|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerGreaterThan|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerGreaterThanOrEqual|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerLessThan|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerLessThanOrEqual|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerIs|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerIsNot|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerIsOneOf|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerIsNotOneOf|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerContains|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerDoesNotContain|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerIsBefore|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerIsAfter|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerIsOn|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerIsOnOrBefore|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerIsOnOrAfter|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerIsEmpty|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerIsNotEmpty|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerContainsWhere|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerDoesNotContainWhere')]
    public PutWorkflowsIdOperatorTriggerEquals|PutWorkflowsIdOperatorTriggerNotEquals|PutWorkflowsIdOperatorTriggerGreaterThan|PutWorkflowsIdOperatorTriggerGreaterThanOrEqual|PutWorkflowsIdOperatorTriggerLessThan|PutWorkflowsIdOperatorTriggerLessThanOrEqual|PutWorkflowsIdOperatorTriggerIs|PutWorkflowsIdOperatorTriggerIsNot|PutWorkflowsIdOperatorTriggerIsOneOf|PutWorkflowsIdOperatorTriggerIsNotOneOf|PutWorkflowsIdOperatorTriggerContains|PutWorkflowsIdOperatorTriggerDoesNotContain|PutWorkflowsIdOperatorTriggerIsBefore|PutWorkflowsIdOperatorTriggerIsAfter|PutWorkflowsIdOperatorTriggerIsOn|PutWorkflowsIdOperatorTriggerIsOnOrBefore|PutWorkflowsIdOperatorTriggerIsOnOrAfter|PutWorkflowsIdOperatorTriggerIsEmpty|PutWorkflowsIdOperatorTriggerIsNotEmpty|PutWorkflowsIdOperatorTriggerContainsWhere|PutWorkflowsIdOperatorTriggerDoesNotContainWhere $operator;

    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\PutWorkflowsIdTriggerRight $right
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('right')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PutWorkflowsIdTriggerRight')]
    public PutWorkflowsIdTriggerRight $right;

    /**
     * @param  string  $id
     * @param  \Juo\AdminAPI\Models\Operations\PutWorkflowsIdTriggerLeft  $left
     * @param  \Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerEquals|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerNotEquals|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerGreaterThan|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerGreaterThanOrEqual|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerLessThan|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerLessThanOrEqual|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerIs|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerIsNot|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerIsOneOf|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerIsNotOneOf|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerContains|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerDoesNotContain|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerIsBefore|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerIsAfter|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerIsOn|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerIsOnOrBefore|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerIsOnOrAfter|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerIsEmpty|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerIsNotEmpty|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerContainsWhere|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdOperatorTriggerDoesNotContainWhere  $operator
     * @param  \Juo\AdminAPI\Models\Operations\PutWorkflowsIdTriggerRight  $right
     * @phpstan-pure
     */
    public function __construct(string $id, PutWorkflowsIdTriggerLeft $left, PutWorkflowsIdOperatorTriggerEquals|PutWorkflowsIdOperatorTriggerNotEquals|PutWorkflowsIdOperatorTriggerGreaterThan|PutWorkflowsIdOperatorTriggerGreaterThanOrEqual|PutWorkflowsIdOperatorTriggerLessThan|PutWorkflowsIdOperatorTriggerLessThanOrEqual|PutWorkflowsIdOperatorTriggerIs|PutWorkflowsIdOperatorTriggerIsNot|PutWorkflowsIdOperatorTriggerIsOneOf|PutWorkflowsIdOperatorTriggerIsNotOneOf|PutWorkflowsIdOperatorTriggerContains|PutWorkflowsIdOperatorTriggerDoesNotContain|PutWorkflowsIdOperatorTriggerIsBefore|PutWorkflowsIdOperatorTriggerIsAfter|PutWorkflowsIdOperatorTriggerIsOn|PutWorkflowsIdOperatorTriggerIsOnOrBefore|PutWorkflowsIdOperatorTriggerIsOnOrAfter|PutWorkflowsIdOperatorTriggerIsEmpty|PutWorkflowsIdOperatorTriggerIsNotEmpty|PutWorkflowsIdOperatorTriggerContainsWhere|PutWorkflowsIdOperatorTriggerDoesNotContainWhere $operator, PutWorkflowsIdTriggerRight $right)
    {
        $this->id = $id;
        $this->left = $left;
        $this->operator = $operator;
        $this->right = $right;
    }
}