<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class PutWorkflowsIdStep
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     * $transitions
     *
     * @var array<\Juo\AdminAPI\Models\Operations\PutWorkflowsIdTransitionAuto|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdTransitionResponse|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdTransitionTimeout> $transitions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('transitions')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Juo\AdminAPI\Models\Operations\PutWorkflowsIdTransitionAuto|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdTransitionResponse|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdTransitionTimeout>')]
    public array $transitions;

    /**
     *
     * @var ?\Juo\AdminAPI\Models\Operations\PutWorkflowsIdAction $action
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('action')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PutWorkflowsIdAction|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PutWorkflowsIdAction $action = null;

    /**
     *
     * @var ?bool $isInitial
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('isInitial')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $isInitial = null;

    /**
     *
     * @var ?bool $isFinal
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('isFinal')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $isFinal = null;

    /**
     *
     * @var ?\Juo\AdminAPI\Models\Operations\PutWorkflowsIdExperimentConfig $experimentConfig
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('experimentConfig')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PutWorkflowsIdExperimentConfig|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PutWorkflowsIdExperimentConfig $experimentConfig = null;

    /**
     * @param  string  $id
     * @param  string  $name
     * @param  array<\Juo\AdminAPI\Models\Operations\PutWorkflowsIdTransitionAuto|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdTransitionResponse|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdTransitionTimeout>  $transitions
     * @param  ?\Juo\AdminAPI\Models\Operations\PutWorkflowsIdAction  $action
     * @param  ?bool  $isInitial
     * @param  ?bool  $isFinal
     * @param  ?\Juo\AdminAPI\Models\Operations\PutWorkflowsIdExperimentConfig  $experimentConfig
     * @phpstan-pure
     */
    public function __construct(string $id, string $name, array $transitions, ?PutWorkflowsIdAction $action = null, ?bool $isInitial = null, ?bool $isFinal = null, ?PutWorkflowsIdExperimentConfig $experimentConfig = null)
    {
        $this->id = $id;
        $this->name = $name;
        $this->transitions = $transitions;
        $this->action = $action;
        $this->isInitial = $isInitial;
        $this->isFinal = $isFinal;
        $this->experimentConfig = $experimentConfig;
    }
}