<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class PutWorkflowsIdTrigger
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var string $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    public string $type;

    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\PutWorkflowsIdCategorySystemEvent|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdCategoryCustomerInitiated|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdCategoryAdminInitiated|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdCategoryTimeBased $category
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('category')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PutWorkflowsIdCategorySystemEvent|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdCategoryCustomerInitiated|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdCategoryAdminInitiated|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdCategoryTimeBased')]
    public PutWorkflowsIdCategorySystemEvent|PutWorkflowsIdCategoryCustomerInitiated|PutWorkflowsIdCategoryAdminInitiated|PutWorkflowsIdCategoryTimeBased $category;

    /**
     *
     * @var ?\Juo\AdminAPI\Models\Operations\PutWorkflowsIdTriggerConditions $conditions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('conditions')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PutWorkflowsIdTriggerConditions|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PutWorkflowsIdTriggerConditions $conditions = null;

    /**
     * @param  string  $id
     * @param  string  $type
     * @param  \Juo\AdminAPI\Models\Operations\PutWorkflowsIdCategorySystemEvent|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdCategoryCustomerInitiated|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdCategoryAdminInitiated|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdCategoryTimeBased  $category
     * @param  ?\Juo\AdminAPI\Models\Operations\PutWorkflowsIdTriggerConditions  $conditions
     * @phpstan-pure
     */
    public function __construct(string $id, string $type, PutWorkflowsIdCategorySystemEvent|PutWorkflowsIdCategoryCustomerInitiated|PutWorkflowsIdCategoryAdminInitiated|PutWorkflowsIdCategoryTimeBased $category, ?PutWorkflowsIdTriggerConditions $conditions = null)
    {
        $this->id = $id;
        $this->type = $type;
        $this->category = $category;
        $this->conditions = $conditions;
    }
}