<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class PutWorkflowsIdAction
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var string $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    public string $type;

    /**
     * $config
     *
     * @var array<string, mixed> $config
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('config')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>')]
    public array $config;

    /**
     * @param  string  $id
     * @param  string  $type
     * @param  array<string, mixed>  $config
     * @phpstan-pure
     */
    public function __construct(string $id, string $type, array $config)
    {
        $this->id = $id;
        $this->type = $type;
        $this->config = $config;
    }
}