<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class PutWorkflowsIdTriggerGroup
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\PutWorkflowsIdLogicTriggerAnd|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdLogicTriggerOr $logic
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('logic')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PutWorkflowsIdLogicTriggerAnd|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdLogicTriggerOr')]
    public PutWorkflowsIdLogicTriggerAnd|PutWorkflowsIdLogicTriggerOr $logic;

    /**
     * $items
     *
     * @var array<\Juo\AdminAPI\Models\Operations\PutWorkflowsIdTriggerItem> $items
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('items')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Juo\AdminAPI\Models\Operations\PutWorkflowsIdTriggerItem>')]
    public array $items;

    /**
     * @param  string  $id
     * @param  \Juo\AdminAPI\Models\Operations\PutWorkflowsIdLogicTriggerAnd|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdLogicTriggerOr  $logic
     * @param  array<\Juo\AdminAPI\Models\Operations\PutWorkflowsIdTriggerItem>  $items
     * @phpstan-pure
     */
    public function __construct(string $id, PutWorkflowsIdLogicTriggerAnd|PutWorkflowsIdLogicTriggerOr $logic, array $items)
    {
        $this->id = $id;
        $this->logic = $logic;
        $this->items = $items;
    }
}