<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class PutWorkflowsIdTransitionGroup1
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var \Juo\AdminAPI\Models\Operations\PutWorkflowsIdTransitionLogicAnd1|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdTransitionLogicOr1 $logic
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('logic')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PutWorkflowsIdTransitionLogicAnd1|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdTransitionLogicOr1')]
    public PutWorkflowsIdTransitionLogicAnd1|PutWorkflowsIdTransitionLogicOr1 $logic;

    /**
     * $items
     *
     * @var array<\Juo\AdminAPI\Models\Operations\PutWorkflowsIdTransitionItem1> $items
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('items')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Juo\AdminAPI\Models\Operations\PutWorkflowsIdTransitionItem1>')]
    public array $items;

    /**
     * @param  string  $id
     * @param  \Juo\AdminAPI\Models\Operations\PutWorkflowsIdTransitionLogicAnd1|\Juo\AdminAPI\Models\Operations\PutWorkflowsIdTransitionLogicOr1  $logic
     * @param  array<\Juo\AdminAPI\Models\Operations\PutWorkflowsIdTransitionItem1>  $items
     * @phpstan-pure
     */
    public function __construct(string $id, PutWorkflowsIdTransitionLogicAnd1|PutWorkflowsIdTransitionLogicOr1 $logic, array $items)
    {
        $this->id = $id;
        $this->logic = $logic;
        $this->items = $items;
    }
}