<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


enum PutWorkflowsIdTransitionOperatorIsOnOrAfter1: string
{
    case IsOnOrAfter = 'is_on_or_after';
}
