<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class Range
{
    /**
     * Start of the date range (ISO 8601 date string, inclusive).
     *
     * @var string $from
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('from')]
    public string $from;

    /**
     * End of the date range (ISO 8601 date string, inclusive).
     *
     * @var string $to
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('to')]
    public string $to;

    /**
     * @param  string  $from
     * @param  string  $to
     * @phpstan-pure
     */
    public function __construct(string $from, string $to)
    {
        $this->from = $from;
        $this->to = $to;
    }
}