<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class RequestBody2
{
    /**
     *
     * @var PostSubscriptionsSubscriptionIdDiscountsTargetShipping|PostSubscriptionsSubscriptionIdDiscountsTargetLine $target
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('target')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PostSubscriptionsSubscriptionIdDiscountsTargetShipping|\Juo\AdminAPI\Models\Operations\PostSubscriptionsSubscriptionIdDiscountsTargetLine')]
    public PostSubscriptionsSubscriptionIdDiscountsTargetShipping|PostSubscriptionsSubscriptionIdDiscountsTargetLine $target;

    /**
     *
     * @var PostSubscriptionsSubscriptionIdDiscountsValueFixedAmount|PostSubscriptionsSubscriptionIdDiscountsValuePercentage $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Operations\PostSubscriptionsSubscriptionIdDiscountsValueFixedAmount|\Juo\AdminAPI\Models\Operations\PostSubscriptionsSubscriptionIdDiscountsValuePercentage')]
    public PostSubscriptionsSubscriptionIdDiscountsValueFixedAmount|PostSubscriptionsSubscriptionIdDiscountsValuePercentage $value;

    /**
     * The title of the discount shown to customers, typically displayed as a discount code.
     *
     * @var ?string $title
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('title')]
    public ?string $title;

    /**
     * The number of billing cycles for which this discount will be applied. After the recurring cycle limit is met the discount will be removed from the subscription.
     *
     * @var ?int $recurringCycleLimit
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('recurringCycleLimit')]
    public ?int $recurringCycleLimit;

    /**
     * @param  PostSubscriptionsSubscriptionIdDiscountsTargetShipping|PostSubscriptionsSubscriptionIdDiscountsTargetLine  $target
     * @param  PostSubscriptionsSubscriptionIdDiscountsValueFixedAmount|PostSubscriptionsSubscriptionIdDiscountsValuePercentage  $value
     * @param  ?string  $title
     * @param  ?int  $recurringCycleLimit
     * @phpstan-pure
     */
    public function __construct(PostSubscriptionsSubscriptionIdDiscountsTargetShipping|PostSubscriptionsSubscriptionIdDiscountsTargetLine $target, PostSubscriptionsSubscriptionIdDiscountsValueFixedAmount|PostSubscriptionsSubscriptionIdDiscountsValuePercentage $value, ?string $title = null, ?int $recurringCycleLimit = null)
    {
        $this->target = $target;
        $this->value = $value;
        $this->title = $title;
        $this->recurringCycleLimit = $recurringCycleLimit;
    }
}