<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Operations;


class Rollups
{
    /**
     * `rollup` values the engine will not reject.
     *
     * @var array<string> $legal
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('legal')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>')]
    public array $legal;

    /**
     * The rollup that answers the question this metric asks. Stricter than `legal`: an `avg` over a cumulative series returns a figure from the middle of the window.
     *
     * @var string $recommended
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('recommended')]
    public string $recommended;

    /**
     * @param  array<string>  $legal
     * @param  string  $recommended
     * @phpstan-pure
     */
    public function __construct(array $legal, string $recommended)
    {
        $this->legal = $legal;
        $this->recommended = $recommended;
    }
}