<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


class Actor
{
    /**
     *
     * @var ScheduleAdjustmentType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Components\ScheduleAdjustmentType')]
    public ScheduleAdjustmentType $type;

    /**
     * The actor identifier, if applicable
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public ?string $id;

    /**
     * @param  ScheduleAdjustmentType  $type
     * @param  ?string  $id
     * @phpstan-pure
     */
    public function __construct(ScheduleAdjustmentType $type, ?string $id = null)
    {
        $this->type = $type;
        $this->id = $id;
    }
}