<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


class Address
{
    /**
     * Customer's first name.
     *
     * @var ?string $firstName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('firstName')]
    public ?string $firstName;

    /**
     * Customer's last name.
     *
     * @var ?string $lastName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('lastName')]
    public ?string $lastName;

    /**
     * Primary street address.
     *
     * @var ?string $address1
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('address1')]
    public ?string $address1;

    /**
     * Additional address information (apartment, suite, etc.)
     *
     * @var ?string $address2
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('address2')]
    public ?string $address2;

    /**
     * Postal/ZIP code.
     *
     * @var ?string $zip
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('zip')]
    public ?string $zip;

    /**
     * City name.
     *
     * @var ?string $city
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('city')]
    public ?string $city;

    /**
     * Full country name.
     *
     * @var ?string $country
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('country')]
    public ?string $country;

    /**
     * Two-letter country code (ISO 3166-1).
     *
     * @var ?string $countryCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('countryCode')]
    public ?string $countryCode;

    /**
     * Province/state code.
     *
     * @var ?string $provinceCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('provinceCode')]
    public ?string $provinceCode;

    /**
     * Full province/state name.
     *
     * @var ?string $province
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('province')]
    public ?string $province;

    /**
     * Contact phone number.
     *
     * @var ?string $phone
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('phone')]
    public ?string $phone;

    /**
     * Company name.
     *
     * @var ?string $company
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('company')]
    public ?string $company;

    /**
     * @param  ?string  $firstName
     * @param  ?string  $lastName
     * @param  ?string  $address1
     * @param  ?string  $address2
     * @param  ?string  $zip
     * @param  ?string  $city
     * @param  ?string  $country
     * @param  ?string  $countryCode
     * @param  ?string  $provinceCode
     * @param  ?string  $province
     * @param  ?string  $phone
     * @param  ?string  $company
     * @phpstan-pure
     */
    public function __construct(?string $firstName = null, ?string $lastName = null, ?string $address1 = null, ?string $address2 = null, ?string $zip = null, ?string $city = null, ?string $country = null, ?string $countryCode = null, ?string $provinceCode = null, ?string $province = null, ?string $phone = null, ?string $company = null)
    {
        $this->firstName = $firstName;
        $this->lastName = $lastName;
        $this->address1 = $address1;
        $this->address2 = $address2;
        $this->zip = $zip;
        $this->city = $city;
        $this->country = $country;
        $this->countryCode = $countryCode;
        $this->provinceCode = $provinceCode;
        $this->province = $province;
        $this->phone = $phone;
        $this->company = $company;
    }
}