<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


class DeliveryMethod
{
    /**
     *
     * @var SubscriptionType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Components\SubscriptionType')]
    public SubscriptionType $type;

    /**
     *
     * @var ?string $title
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('title')]
    public ?string $title;

    /**
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    public ?string $description;

    /**
     * @param  SubscriptionType  $type
     * @param  ?string  $title
     * @param  ?string  $description
     * @phpstan-pure
     */
    public function __construct(SubscriptionType $type, ?string $title = null, ?string $description = null)
    {
        $this->type = $type;
        $this->title = $title;
        $this->description = $description;
    }
}