<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


class ExperimentConfig
{
    /**
     * $variants
     *
     * @var array<\Juo\AdminAPI\Models\Components\WorkflowVariant> $variants
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('variants')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Juo\AdminAPI\Models\Components\WorkflowVariant>')]
    public array $variants;

    /**
     *
     * @var ?\Juo\AdminAPI\Models\Components\Settings $settings
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('settings')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Components\Settings|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Settings $settings = null;

    /**
     *
     * @var ?string $primaryMetricId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('primaryMetricId')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $primaryMetricId = null;

    /**
     * @param  array<\Juo\AdminAPI\Models\Components\WorkflowVariant>  $variants
     * @param  ?\Juo\AdminAPI\Models\Components\Settings  $settings
     * @param  ?string  $primaryMetricId
     * @phpstan-pure
     */
    public function __construct(array $variants, ?Settings $settings = null, ?string $primaryMetricId = null)
    {
        $this->variants = $variants;
        $this->settings = $settings;
        $this->primaryMetricId = $primaryMetricId;
    }
}