<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


enum FieldOrderItemSellingPlanID: string
{
    case OrderItemSellingPlanId = 'order_item.selling_plan_id';
}
