<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


enum FieldEventCycleIndex: string
{
    case EventCycleIndex = 'event.cycle_index';
}
