<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


enum FieldSubscriptionHasItemWithPlanID: string
{
    case SubscriptionHasItemWithPlanId = 'subscription.has_item_with_plan_id';
}
