<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


enum FieldSubscriptionBillingIntervalCount: string
{
    case SubscriptionBillingIntervalCount = 'subscription.billing_interval_count';
}
