<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


enum FieldOrderItemIsFirstOrder: string
{
    case OrderItemIsFirstOrder = 'order_item.is_first_order';
}
