<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


enum FieldSubscriptionFirstPurchaseAt: string
{
    case SubscriptionFirstPurchaseAt = 'subscription.first_purchase_at';
}
