<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


enum FieldSubscriptionItemIsRecurring: string
{
    case SubscriptionItemIsRecurring = 'subscription_item.is_recurring';
}
