<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


class InstrumentSepaDirectDebit
{
    /**
     *
     * @var \Juo\AdminAPI\Models\Components\TypeSepaDirectDebit $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Components\TypeSepaDirectDebit')]
    public TypeSepaDirectDebit $type;

    /**
     * Full name of the account holder.
     *
     * @var string $consumerName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('consumerName')]
    public string $consumerName;

    /**
     * BIC code.
     *
     * @var string $consumerBic
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('consumerBic')]
    public string $consumerBic;

    /**
     * Masked IBAN.
     *
     * @var string $maskedConsumerAccount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('maskedConsumerAccount')]
    public string $maskedConsumerAccount;

    /**
     * @param  \Juo\AdminAPI\Models\Components\TypeSepaDirectDebit  $type
     * @param  string  $consumerName
     * @param  string  $consumerBic
     * @param  string  $maskedConsumerAccount
     * @phpstan-pure
     */
    public function __construct(TypeSepaDirectDebit $type, string $consumerName, string $consumerBic, string $maskedConsumerAccount)
    {
        $this->type = $type;
        $this->consumerName = $consumerName;
        $this->consumerBic = $consumerBic;
        $this->maskedConsumerAccount = $maskedConsumerAccount;
    }
}