<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


class InstrumentBlik
{
    /**
     *
     * @var TypeBlik $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Components\TypeBlik')]
    public TypeBlik $type;

    /**
     * @param  TypeBlik  $type
     * @phpstan-pure
     */
    public function __construct(TypeBlik $type)
    {
        $this->type = $type;
    }
}