<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


class InstrumentMbway
{
    /**
     *
     * @var TypeMbway $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Components\TypeMbway')]
    public TypeMbway $type;

    /**
     *
     * @var ?string $phone
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('phone')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $phone = null;

    /**
     * @param  TypeMbway  $type
     * @param  ?string  $phone
     * @phpstan-pure
     */
    public function __construct(TypeMbway $type, ?string $phone = null)
    {
        $this->type = $type;
        $this->phone = $phone;
    }
}