<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


class InstrumentCreditCard
{
    /**
     *
     * @var TypeCreditCard $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Components\TypeCreditCard')]
    public TypeCreditCard $type;

    /**
     * Credit card network name.
     *
     * @var string $brand
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('brand')]
    public string $brand;

    /**
     * Masked card number.
     *
     * @var string $maskedNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('maskedNumber')]
    public string $maskedNumber;

    /**
     * @param  TypeCreditCard  $type
     * @param  string  $brand
     * @param  string  $maskedNumber
     * @phpstan-pure
     */
    public function __construct(TypeCreditCard $type, string $brand, string $maskedNumber)
    {
        $this->type = $type;
        $this->brand = $brand;
        $this->maskedNumber = $maskedNumber;
    }
}