<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


class InstrumentShopPay
{
    /**
     *
     * @var \Juo\AdminAPI\Models\Components\TypeShopPay $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Components\TypeShopPay')]
    public TypeShopPay $type;

    /**
     * Masked card number.
     *
     * @var string $maskedNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('maskedNumber')]
    public string $maskedNumber;

    /**
     * @param  \Juo\AdminAPI\Models\Components\TypeShopPay  $type
     * @param  string  $maskedNumber
     * @phpstan-pure
     */
    public function __construct(TypeShopPay $type, string $maskedNumber)
    {
        $this->type = $type;
        $this->maskedNumber = $maskedNumber;
    }
}