<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


class Matcher
{
    /**
     *
     * @var string $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    public string $type;

    /**
     *
     * @var mixed $input
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('input')]
    #[\Speakeasy\Serializer\Annotation\Type('mixed')]
    public mixed $input;

    /**
     * @param  string  $type
     * @param  mixed  $input
     * @phpstan-pure
     */
    public function __construct(string $type, mixed $input)
    {
        $this->type = $type;
        $this->input = $input;
    }
}