<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


class Order
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var \DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdAt')]
    public \DateTime $createdAt;

    /**
     *
     * @var string $currencyCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currencyCode')]
    public string $currencyCode;

    /**
     * `recurring` is a scheduled renewal order, `checkout` the order that created the subscription, and `instant` a one-off purchase the customer made outside the schedule (an instant order) — it carries no billing cycle.
     *
     * @var \Juo\AdminAPI\Models\Components\TypeCheckout|\Juo\AdminAPI\Models\Components\TypeRecurring|\Juo\AdminAPI\Models\Components\TypeInstant $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Components\TypeCheckout|\Juo\AdminAPI\Models\Components\TypeRecurring|\Juo\AdminAPI\Models\Components\TypeInstant')]
    public TypeCheckout|TypeRecurring|TypeInstant $type;

    /**
     *
     * @var float $deliveryPrice
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('deliveryPrice')]
    public float $deliveryPrice;

    /**
     * $items
     *
     * @var array<\Juo\AdminAPI\Models\Components\OrderItem> $items
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('items')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Juo\AdminAPI\Models\Components\OrderItem>')]
    public array $items;

    /**
     * $discounts
     *
     * @var array<\Juo\AdminAPI\Models\Components\OrderDiscount> $discounts
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('discounts')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Juo\AdminAPI\Models\Components\OrderDiscount>')]
    public array $discounts;

    /**
     * $subscriptionIds
     *
     * @var array<string> $subscriptionIds
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subscriptionIds')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>')]
    public array $subscriptionIds;

    /**
     * Arbitrary key-value pairs attached to this order.
     *
     * @var array<\Juo\AdminAPI\Models\Components\OrderCustomAttribute> $customAttributes
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('customAttributes')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Juo\AdminAPI\Models\Components\OrderCustomAttribute>')]
    public array $customAttributes;

    /**
     *
     * @var ?\DateTime $placedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('placedAt')]
    public ?\DateTime $placedAt;

    /**
     *
     * @var ?float $subtotal
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subtotal')]
    public ?float $subtotal;

    /**
     *
     * @var ?float $totalPrice
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('totalPrice')]
    public ?float $totalPrice;

    /**
     *
     * @var ?float $taxesAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('taxesAmount')]
    public ?float $taxesAmount;

    /**
     *
     * @var ?bool $taxesIncluded
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('taxesIncluded')]
    public ?bool $taxesIncluded;

    /**
     *
     * @var ?string $customerId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('customerId')]
    public ?string $customerId;

    /**
     *
     * @var ?string $externalId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('externalId')]
    public ?string $externalId;

    /**
     * @param  string  $id
     * @param  \DateTime  $createdAt
     * @param  string  $currencyCode
     * @param  \Juo\AdminAPI\Models\Components\TypeCheckout|\Juo\AdminAPI\Models\Components\TypeRecurring|\Juo\AdminAPI\Models\Components\TypeInstant  $type
     * @param  float  $deliveryPrice
     * @param  array<\Juo\AdminAPI\Models\Components\OrderItem>  $items
     * @param  array<\Juo\AdminAPI\Models\Components\OrderDiscount>  $discounts
     * @param  array<string>  $subscriptionIds
     * @param  array<\Juo\AdminAPI\Models\Components\OrderCustomAttribute>  $customAttributes
     * @param  ?\DateTime  $placedAt
     * @param  ?float  $subtotal
     * @param  ?float  $totalPrice
     * @param  ?float  $taxesAmount
     * @param  ?bool  $taxesIncluded
     * @param  ?string  $customerId
     * @param  ?string  $externalId
     * @phpstan-pure
     */
    public function __construct(string $id, \DateTime $createdAt, string $currencyCode, TypeCheckout|TypeRecurring|TypeInstant $type, float $deliveryPrice, array $items, array $discounts, array $subscriptionIds, array $customAttributes, ?\DateTime $placedAt = null, ?float $subtotal = null, ?float $totalPrice = null, ?float $taxesAmount = null, ?bool $taxesIncluded = null, ?string $customerId = null, ?string $externalId = null)
    {
        $this->id = $id;
        $this->createdAt = $createdAt;
        $this->currencyCode = $currencyCode;
        $this->type = $type;
        $this->deliveryPrice = $deliveryPrice;
        $this->items = $items;
        $this->discounts = $discounts;
        $this->subscriptionIds = $subscriptionIds;
        $this->customAttributes = $customAttributes;
        $this->placedAt = $placedAt;
        $this->subtotal = $subtotal;
        $this->totalPrice = $totalPrice;
        $this->taxesAmount = $taxesAmount;
        $this->taxesIncluded = $taxesIncluded;
        $this->customerId = $customerId;
        $this->externalId = $externalId;
    }
}