<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


class OrderDiscount
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var \Juo\AdminAPI\Models\Components\OrderDiscountTargetLine|\Juo\AdminAPI\Models\Components\OrderDiscountTargetShipping $target
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('target')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Components\OrderDiscountTargetLine|\Juo\AdminAPI\Models\Components\OrderDiscountTargetShipping')]
    public OrderDiscountTargetLine|OrderDiscountTargetShipping $target;

    /**
     *
     * @var \Juo\AdminAPI\Models\Components\OrderDiscountValuePercentage|\Juo\AdminAPI\Models\Components\OrderDiscountValueFixedAmount $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Components\OrderDiscountValuePercentage|\Juo\AdminAPI\Models\Components\OrderDiscountValueFixedAmount')]
    public OrderDiscountValuePercentage|OrderDiscountValueFixedAmount $value;

    /**
     *
     * @var \Juo\AdminAPI\Models\Components\OrderDiscountEntitledItems1|\Juo\AdminAPI\Models\Components\OrderDiscountEntitledItems2 $entitledItems
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('entitledItems')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Components\OrderDiscountEntitledItems1|\Juo\AdminAPI\Models\Components\OrderDiscountEntitledItems2')]
    public OrderDiscountEntitledItems1|OrderDiscountEntitledItems2 $entitledItems;

    /**
     *
     * @var ?string $title
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('title')]
    public ?string $title;

    /**
     * SubscriptionDiscount `id` when not expanded, or the full `SubscriptionDiscount` object when the field name is included in the `expand` query parameter. Can be null.
     *
     * @var string|\Juo\AdminAPI\Models\Components\SubscriptionDiscount|null $subscriptionDiscount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subscriptionDiscount')]
    #[\Speakeasy\Serializer\Annotation\Type('string|\Juo\AdminAPI\Models\Components\SubscriptionDiscount|null')]
    public string|SubscriptionDiscount|null $subscriptionDiscount;

    /**
     * @param  string  $id
     * @param  \Juo\AdminAPI\Models\Components\OrderDiscountTargetLine|\Juo\AdminAPI\Models\Components\OrderDiscountTargetShipping  $target
     * @param  \Juo\AdminAPI\Models\Components\OrderDiscountValuePercentage|\Juo\AdminAPI\Models\Components\OrderDiscountValueFixedAmount  $value
     * @param  \Juo\AdminAPI\Models\Components\OrderDiscountEntitledItems1|\Juo\AdminAPI\Models\Components\OrderDiscountEntitledItems2  $entitledItems
     * @param  ?string  $title
     * @param  string|\Juo\AdminAPI\Models\Components\SubscriptionDiscount|null  $subscriptionDiscount
     * @phpstan-pure
     */
    public function __construct(string $id, OrderDiscountTargetLine|OrderDiscountTargetShipping $target, OrderDiscountValuePercentage|OrderDiscountValueFixedAmount $value, OrderDiscountEntitledItems1|OrderDiscountEntitledItems2 $entitledItems, ?string $title = null, string|SubscriptionDiscount|null $subscriptionDiscount = null)
    {
        $this->id = $id;
        $this->target = $target;
        $this->value = $value;
        $this->entitledItems = $entitledItems;
        $this->title = $title;
        $this->subscriptionDiscount = $subscriptionDiscount;
    }
}