<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


class Product
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var string $title
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('title')]
    public string $title;

    /**
     *
     * @var ?ProductImage $image
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('image')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Components\ProductImage|null')]
    public ?ProductImage $image;

    /**
     * @param  string  $id
     * @param  string  $title
     * @param  ?ProductImage  $image
     * @phpstan-pure
     */
    public function __construct(string $id, string $title, ?ProductImage $image = null)
    {
        $this->id = $id;
        $this->title = $title;
        $this->image = $image;
    }
}