<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


class ProductVariantImage
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var string $url
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('url')]
    public string $url;

    /**
     *
     * @var ?string $altText
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('altText')]
    public ?string $altText;

    /**
     * @param  string  $id
     * @param  string  $url
     * @param  ?string  $altText
     * @phpstan-pure
     */
    public function __construct(string $id, string $url, ?string $altText = null)
    {
        $this->id = $id;
        $this->url = $url;
        $this->altText = $altText;
    }
}