<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


class ProductVariant
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var string $title
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('title')]
    public string $title;

    /**
     *
     * @var float $price
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('price')]
    public float $price;

    /**
     * $purchaseOptions
     *
     * @var array<\Juo\AdminAPI\Models\Components\PurchaseOption> $purchaseOptions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('purchaseOptions')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Juo\AdminAPI\Models\Components\PurchaseOption>')]
    public array $purchaseOptions;

    /**
     * Product `id` when not expanded, or the full `Product` object when the field name is included in the `expand` query parameter.
     *
     * @var string|\Juo\AdminAPI\Models\Components\Product $product
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('product')]
    #[\Speakeasy\Serializer\Annotation\Type('string|\Juo\AdminAPI\Models\Components\Product')]
    public string|Product $product;

    /**
     * Subscription plan group IDs associated with this variant
     *
     * @var array<string> $planGroups
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('planGroups')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>')]
    public array $planGroups;

    /**
     *
     * @var ?\Juo\AdminAPI\Models\Components\ProductVariantImage $image
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('image')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Components\ProductVariantImage|null')]
    public ?ProductVariantImage $image;

    /**
     * @param  string  $id
     * @param  string  $title
     * @param  float  $price
     * @param  array<\Juo\AdminAPI\Models\Components\PurchaseOption>  $purchaseOptions
     * @param  string|\Juo\AdminAPI\Models\Components\Product  $product
     * @param  array<string>  $planGroups
     * @param  ?\Juo\AdminAPI\Models\Components\ProductVariantImage  $image
     * @phpstan-pure
     */
    public function __construct(string $id, string $title, float $price, array $purchaseOptions, string|Product $product, array $planGroups, ?ProductVariantImage $image = null)
    {
        $this->id = $id;
        $this->title = $title;
        $this->price = $price;
        $this->purchaseOptions = $purchaseOptions;
        $this->product = $product;
        $this->planGroups = $planGroups;
        $this->image = $image;
    }
}