<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


enum ProductVariantIntervalEnum: string
{
    case Day = 'DAY';
    case Month = 'MONTH';
    case Week = 'WEEK';
    case Year = 'YEAR';
}
