<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


class ProductVariant
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var string $title
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('title')]
    public string $title;

    /**
     * This field is expandable.
     *
     * @var string|Product $product
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('product')]
    #[\Speakeasy\Serializer\Annotation\Type('string|\Juo\AdminAPI\Models\Components\Product')]
    public string|Product $product;

    /**
     *
     * @var ?ProductVariantImage $image
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('image')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Components\ProductVariantImage|null')]
    public ?ProductVariantImage $image;

    /**
     * @param  string  $id
     * @param  string  $title
     * @param  string|Product  $product
     * @param  ?ProductVariantImage  $image
     * @phpstan-pure
     */
    public function __construct(string $id, string $title, string|Product $product, ?ProductVariantImage $image = null)
    {
        $this->id = $id;
        $this->title = $title;
        $this->product = $product;
        $this->image = $image;
    }
}