<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


class ScheduleOrderDiscountValueFixedAmount
{
    /**
     *
     * @var \Juo\AdminAPI\Models\Components\ScheduleOrderDiscountTypeFixedAmount $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Components\ScheduleOrderDiscountTypeFixedAmount')]
    public ScheduleOrderDiscountTypeFixedAmount $type;

    /**
     *
     * @var float $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    public float $amount;

    /**
     *
     * @var bool $appliesOnEachItem
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('appliesOnEachItem')]
    public bool $appliesOnEachItem;

    /**
     * @param  \Juo\AdminAPI\Models\Components\ScheduleOrderDiscountTypeFixedAmount  $type
     * @param  float  $amount
     * @param  bool  $appliesOnEachItem
     * @phpstan-pure
     */
    public function __construct(ScheduleOrderDiscountTypeFixedAmount $type, float $amount, bool $appliesOnEachItem)
    {
        $this->type = $type;
        $this->amount = $amount;
        $this->appliesOnEachItem = $appliesOnEachItem;
    }
}