<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


class ScheduleOrderItem
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var string $title
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('title')]
    public string $title;

    /**
     *
     * @var int $quantity
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('quantity')]
    public int $quantity;

    /**
     *
     * @var float $price
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('price')]
    public float $price;

    /**
     *
     * @var float $totalPrice
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('totalPrice')]
    public float $totalPrice;

    /**
     * $customAttributes
     *
     * @var array<\Juo\AdminAPI\Models\Components\CustomAttribute> $customAttributes
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('customAttributes')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Juo\AdminAPI\Models\Components\CustomAttribute>')]
    public array $customAttributes;

    /**
     *
     * @var ?string $subtitle
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subtitle')]
    public ?string $subtitle;

    /**
     * This field is expandable.
     *
     * @var string|\Juo\AdminAPI\Models\Components\ProductVariant|null $variant
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('variant')]
    #[\Speakeasy\Serializer\Annotation\Type('string|\Juo\AdminAPI\Models\Components\ProductVariant|null')]
    public string|ProductVariant|null $variant;

    /**
     * This field is expandable.
     *
     * @var string|\Juo\AdminAPI\Models\Components\Product|null $product
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('product')]
    #[\Speakeasy\Serializer\Annotation\Type('string|\Juo\AdminAPI\Models\Components\Product|null')]
    public string|Product|null $product;

    /**
     * This field is expandable.
     *
     * @var string|\Juo\AdminAPI\Models\Components\Subscription|null $subscription
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subscription')]
    #[\Speakeasy\Serializer\Annotation\Type('string|\Juo\AdminAPI\Models\Components\Subscription|null')]
    public string|Subscription|null $subscription;

    /**
     * This field is expandable.
     *
     * @var string|\Juo\AdminAPI\Models\Components\SubscriptionItem|null $subscriptionItem
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subscriptionItem')]
    #[\Speakeasy\Serializer\Annotation\Type('string|\Juo\AdminAPI\Models\Components\SubscriptionItem|null')]
    public string|SubscriptionItem|null $subscriptionItem;

    /**
     *
     * @var ?string $parentProductId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('parentProductId')]
    public ?string $parentProductId;

    /**
     *
     * @var ?string $parentLineId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('parentLineId')]
    public ?string $parentLineId;

    /**
     * @param  string  $id
     * @param  string  $title
     * @param  int  $quantity
     * @param  float  $price
     * @param  float  $totalPrice
     * @param  array<\Juo\AdminAPI\Models\Components\CustomAttribute>  $customAttributes
     * @param  ?string  $subtitle
     * @param  string|\Juo\AdminAPI\Models\Components\ProductVariant|null  $variant
     * @param  string|\Juo\AdminAPI\Models\Components\Product|null  $product
     * @param  string|\Juo\AdminAPI\Models\Components\Subscription|null  $subscription
     * @param  string|\Juo\AdminAPI\Models\Components\SubscriptionItem|null  $subscriptionItem
     * @param  ?string  $parentProductId
     * @param  ?string  $parentLineId
     * @phpstan-pure
     */
    public function __construct(string $id, string $title, int $quantity, float $price, float $totalPrice, array $customAttributes, ?string $subtitle = null, string|ProductVariant|null $variant = null, string|Product|null $product = null, string|Subscription|null $subscription = null, string|SubscriptionItem|null $subscriptionItem = null, ?string $parentProductId = null, ?string $parentLineId = null)
    {
        $this->id = $id;
        $this->title = $title;
        $this->quantity = $quantity;
        $this->price = $price;
        $this->totalPrice = $totalPrice;
        $this->customAttributes = $customAttributes;
        $this->subtitle = $subtitle;
        $this->variant = $variant;
        $this->product = $product;
        $this->subscription = $subscription;
        $this->subscriptionItem = $subscriptionItem;
        $this->parentProductId = $parentProductId;
        $this->parentLineId = $parentLineId;
    }
}