<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


class ScheduleOrder
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var string $customerId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('customerId')]
    public string $customerId;

    /**
     *
     * @var string $currencyCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currencyCode')]
    public string $currencyCode;

    /**
     *
     * @var bool $skipped
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('skipped')]
    public bool $skipped;

    /**
     *
     * @var \DateTime $date
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('date')]
    public \DateTime $date;

    /**
     *
     * @var int $cycleIndex
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('cycleIndex')]
    public int $cycleIndex;

    /**
     *
     * @var float $subtotal
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subtotal')]
    public float $subtotal;

    /**
     *
     * @var float $deliveryPrice
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('deliveryPrice')]
    public float $deliveryPrice;

    /**
     * $items
     *
     * @var array<\Juo\AdminAPI\Models\Components\ScheduleOrderItem> $items
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('items')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Juo\AdminAPI\Models\Components\ScheduleOrderItem>')]
    public array $items;

    /**
     * $discounts
     *
     * @var array<\Juo\AdminAPI\Models\Components\ScheduleOrderDiscount> $discounts
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('discounts')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Juo\AdminAPI\Models\Components\ScheduleOrderDiscount>')]
    public array $discounts;

    /**
     *
     * @var ?\Juo\AdminAPI\Models\Components\DeliveryAddress $deliveryAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('deliveryAddress')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Components\DeliveryAddress|null')]
    public ?DeliveryAddress $deliveryAddress;

    /**
     *
     * @var ?string $paymentMethodId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('paymentMethodId')]
    public ?string $paymentMethodId;

    /**
     * CustomerPaymentMethod `id` when not expanded, or the full `CustomerPaymentMethod` object when the field name is included in the `expand` query parameter. Can be null.
     *
     * @var string|\Juo\AdminAPI\Models\Components\CustomerPaymentMethod|null $paymentMethod
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('paymentMethod')]
    #[\Speakeasy\Serializer\Annotation\Type('string|\Juo\AdminAPI\Models\Components\CustomerPaymentMethod|null')]
    public string|CustomerPaymentMethod|null $paymentMethod;

    /**
     * @param  string  $id
     * @param  string  $customerId
     * @param  string  $currencyCode
     * @param  bool  $skipped
     * @param  \DateTime  $date
     * @param  int  $cycleIndex
     * @param  float  $subtotal
     * @param  float  $deliveryPrice
     * @param  array<\Juo\AdminAPI\Models\Components\ScheduleOrderItem>  $items
     * @param  array<\Juo\AdminAPI\Models\Components\ScheduleOrderDiscount>  $discounts
     * @param  ?\Juo\AdminAPI\Models\Components\DeliveryAddress  $deliveryAddress
     * @param  ?string  $paymentMethodId
     * @param  string|\Juo\AdminAPI\Models\Components\CustomerPaymentMethod|null  $paymentMethod
     * @phpstan-pure
     */
    public function __construct(string $id, string $customerId, string $currencyCode, bool $skipped, \DateTime $date, int $cycleIndex, float $subtotal, float $deliveryPrice, array $items, array $discounts, ?DeliveryAddress $deliveryAddress = null, ?string $paymentMethodId = null, string|CustomerPaymentMethod|null $paymentMethod = null)
    {
        $this->id = $id;
        $this->customerId = $customerId;
        $this->currencyCode = $currencyCode;
        $this->skipped = $skipped;
        $this->date = $date;
        $this->cycleIndex = $cycleIndex;
        $this->subtotal = $subtotal;
        $this->deliveryPrice = $deliveryPrice;
        $this->items = $items;
        $this->discounts = $discounts;
        $this->deliveryAddress = $deliveryAddress;
        $this->paymentMethodId = $paymentMethodId;
        $this->paymentMethod = $paymentMethod;
    }
}