<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


class ScheduleOrderDiscount
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var string $title
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('title')]
    public string $title;

    /**
     *
     * @var \Juo\AdminAPI\Models\Components\ScheduleOrderDiscountTargetLine|\Juo\AdminAPI\Models\Components\ScheduleOrderDiscountTargetShipping $target
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('target')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Components\ScheduleOrderDiscountTargetLine|\Juo\AdminAPI\Models\Components\ScheduleOrderDiscountTargetShipping')]
    public ScheduleOrderDiscountTargetLine|ScheduleOrderDiscountTargetShipping $target;

    /**
     *
     * @var \Juo\AdminAPI\Models\Components\ScheduleOrderDiscountValuePercentage|\Juo\AdminAPI\Models\Components\ScheduleOrderDiscountValueFixedAmount $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Components\ScheduleOrderDiscountValuePercentage|\Juo\AdminAPI\Models\Components\ScheduleOrderDiscountValueFixedAmount')]
    public ScheduleOrderDiscountValuePercentage|ScheduleOrderDiscountValueFixedAmount $value;

    /**
     *
     * @var \Juo\AdminAPI\Models\Components\ScheduleOrderDiscountEntitledItems1|\Juo\AdminAPI\Models\Components\ScheduleOrderDiscountEntitledItems2 $entitledItems
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('entitledItems')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Components\ScheduleOrderDiscountEntitledItems1|\Juo\AdminAPI\Models\Components\ScheduleOrderDiscountEntitledItems2')]
    public ScheduleOrderDiscountEntitledItems1|ScheduleOrderDiscountEntitledItems2 $entitledItems;

    /**
     *
     * @var ?string $subscriptionId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subscriptionId')]
    public ?string $subscriptionId;

    /**
     * @param  string  $id
     * @param  string  $title
     * @param  \Juo\AdminAPI\Models\Components\ScheduleOrderDiscountTargetLine|\Juo\AdminAPI\Models\Components\ScheduleOrderDiscountTargetShipping  $target
     * @param  \Juo\AdminAPI\Models\Components\ScheduleOrderDiscountValuePercentage|\Juo\AdminAPI\Models\Components\ScheduleOrderDiscountValueFixedAmount  $value
     * @param  \Juo\AdminAPI\Models\Components\ScheduleOrderDiscountEntitledItems1|\Juo\AdminAPI\Models\Components\ScheduleOrderDiscountEntitledItems2  $entitledItems
     * @param  ?string  $subscriptionId
     * @phpstan-pure
     */
    public function __construct(string $id, string $title, ScheduleOrderDiscountTargetLine|ScheduleOrderDiscountTargetShipping $target, ScheduleOrderDiscountValuePercentage|ScheduleOrderDiscountValueFixedAmount $value, ScheduleOrderDiscountEntitledItems1|ScheduleOrderDiscountEntitledItems2 $entitledItems, ?string $subscriptionId = null)
    {
        $this->id = $id;
        $this->title = $title;
        $this->target = $target;
        $this->value = $value;
        $this->entitledItems = $entitledItems;
        $this->subscriptionId = $subscriptionId;
    }
}