<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


class ScheduleOrderDiscountEntitledItems2
{
    /**
     * $items
     *
     * @var array<string> $items
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('items')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>')]
    public array $items;

    /**
     *
     * @var bool $all
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('all')]
    public bool $all;

    /**
     * @param  bool  $all
     * @param  array<string>  $items
     * @phpstan-pure
     */
    public function __construct(array $items, bool $all = false)
    {
        $this->items = $items;
        $this->all = $all;
    }
}