<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;

use Juo\AdminAPI\Utils\SpeakeasyMetadata;
class Security
{
    /**
     *
     * @var string $adminApiKey
     */
    #[SpeakeasyMetadata('security:scheme=true,type=apiKey,subtype=header,name=X-Juo-Admin-Api-Key')]
    public string $adminApiKey;

    /**
     * @param  string  $adminApiKey
     * @phpstan-pure
     */
    public function __construct(string $adminApiKey)
    {
        $this->adminApiKey = $adminApiKey;
    }
}