<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


class Settings
{
    /**
     *
     * @var \Juo\AdminAPI\Models\Components\StatisticalMethod $statisticalMethod
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('statisticalMethod')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Components\StatisticalMethod')]
    public StatisticalMethod $statisticalMethod;

    /**
     *
     * @var float $significanceLevel
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('significanceLevel')]
    public float $significanceLevel;

    /**
     * @param  \Juo\AdminAPI\Models\Components\StatisticalMethod  $statisticalMethod
     * @param  float  $significanceLevel
     * @phpstan-pure
     */
    public function __construct(StatisticalMethod $statisticalMethod, float $significanceLevel)
    {
        $this->statisticalMethod = $statisticalMethod;
        $this->significanceLevel = $significanceLevel;
    }
}