<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


enum Status: string
{
    case Active = 'active';
    case Paused = 'paused';
    case Canceled = 'canceled';
    case Failed = 'failed';
    case Expired = 'expired';
    case Merged = 'merged';
}
