<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


/** SubscriptionDeliveryPolicy - How often shipments are dispatched. Usually matches the billing policy. */
class SubscriptionDeliveryPolicy
{
    /**
     * Delivery frequency unit. One of: `WEEK`, `MONTH`, `YEAR`, `DAY`.
     *
     * @var \Juo\AdminAPI\Models\Components\SubscriptionDeliveryPolicyInterval $interval
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('interval')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Components\SubscriptionDeliveryPolicyInterval')]
    public SubscriptionDeliveryPolicyInterval $interval;

    /**
     * Number of interval units between deliveries.
     *
     * @var int $intervalCount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('intervalCount')]
    public int $intervalCount;

    /**
     * @param  \Juo\AdminAPI\Models\Components\SubscriptionDeliveryPolicyInterval  $interval
     * @param  int  $intervalCount
     * @phpstan-pure
     */
    public function __construct(SubscriptionDeliveryPolicyInterval $interval, int $intervalCount)
    {
        $this->interval = $interval;
        $this->intervalCount = $intervalCount;
    }
}