<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


/** SubscriptionBillingPolicy - How often and when the subscription is billed. */
class SubscriptionBillingPolicy
{
    /**
     * Billing frequency unit. One of: `WEEK`, `MONTH`, `YEAR`, `DAY`.
     *
     * @var \Juo\AdminAPI\Models\Components\SubscriptionBillingPolicyInterval $interval
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('interval')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Components\SubscriptionBillingPolicyInterval')]
    public SubscriptionBillingPolicyInterval $interval;

    /**
     * Number of interval units between billing cycles.
     *
     * @var int $intervalCount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('intervalCount')]
    public int $intervalCount;

    /**
     * @param  \Juo\AdminAPI\Models\Components\SubscriptionBillingPolicyInterval  $interval
     * @param  int  $intervalCount
     * @phpstan-pure
     */
    public function __construct(SubscriptionBillingPolicyInterval $interval, int $intervalCount)
    {
        $this->interval = $interval;
        $this->intervalCount = $intervalCount;
    }
}