<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


class SubscriptionItem
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var SubscriptionItemResource $resource
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('resource')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Components\SubscriptionItemResource')]
    public SubscriptionItemResource $resource;

    /**
     *
     * @var string $title
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('title')]
    public string $title;

    /**
     *
     * @var int $quantity
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('quantity')]
    public int $quantity;

    /**
     * Final item price including all discounts and taxes
     *
     * @var float $totalPrice
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('totalPrice')]
    public float $totalPrice;

    /**
     * Matches the variant title in most cases
     *
     * @var ?string $subtitle
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subtitle')]
    public ?string $subtitle;

    /**
     * The number of billing cycles for which this item will be applied. After the recurring cycle limit is met the item will be removed from the subscription.
     *
     * @var ?int $recurringCycleLimit
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('recurringCycleLimit')]
    public ?int $recurringCycleLimit;

    /**
     * Cancellation date of the item.
     *
     * @var ?\DateTime $canceledAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('canceledAt')]
    public ?\DateTime $canceledAt;

    /**
     *
     * @var ?BillingPolicy $billingPolicy
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('billingPolicy')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Components\BillingPolicy|null')]
    public ?BillingPolicy $billingPolicy;

    /**
     *
     * @var ?DeliveryPolicy $deliveryPolicy
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('deliveryPolicy')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Components\DeliveryPolicy|null')]
    public ?DeliveryPolicy $deliveryPolicy;

    /**
     * This field is expandable.
     *
     * @var string|ProductVariant|null $variant
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('variant')]
    #[\Speakeasy\Serializer\Annotation\Type('string|\Juo\AdminAPI\Models\Components\ProductVariant|null')]
    public string|ProductVariant|null $variant;

    /**
     * This field is expandable.
     *
     * @var string|Product|null $product
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('product')]
    #[\Speakeasy\Serializer\Annotation\Type('string|\Juo\AdminAPI\Models\Components\Product|null')]
    public string|Product|null $product;

    /**
     * @param  string  $id
     * @param  SubscriptionItemResource  $resource
     * @param  string  $title
     * @param  int  $quantity
     * @param  float  $totalPrice
     * @param  ?string  $subtitle
     * @param  ?int  $recurringCycleLimit
     * @param  ?\DateTime  $canceledAt
     * @param  ?BillingPolicy  $billingPolicy
     * @param  ?DeliveryPolicy  $deliveryPolicy
     * @param  string|ProductVariant|null  $variant
     * @param  string|Product|null  $product
     * @phpstan-pure
     */
    public function __construct(string $id, SubscriptionItemResource $resource, string $title, int $quantity, float $totalPrice, ?string $subtitle = null, ?int $recurringCycleLimit = null, ?\DateTime $canceledAt = null, ?BillingPolicy $billingPolicy = null, ?DeliveryPolicy $deliveryPolicy = null, string|ProductVariant|null $variant = null, string|Product|null $product = null)
    {
        $this->id = $id;
        $this->resource = $resource;
        $this->title = $title;
        $this->quantity = $quantity;
        $this->totalPrice = $totalPrice;
        $this->subtitle = $subtitle;
        $this->recurringCycleLimit = $recurringCycleLimit;
        $this->canceledAt = $canceledAt;
        $this->billingPolicy = $billingPolicy;
        $this->deliveryPolicy = $deliveryPolicy;
        $this->variant = $variant;
        $this->product = $product;
    }
}