<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


class SubscriptionDiscountValuePercentage
{
    /**
     *
     * @var float $percentage
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('percentage')]
    public float $percentage;

    /**
     *
     * @var SubscriptionDiscountTypePercentage $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Components\SubscriptionDiscountTypePercentage')]
    public SubscriptionDiscountTypePercentage $type;

    /**
     * @param  float  $percentage
     * @param  SubscriptionDiscountTypePercentage  $type
     * @phpstan-pure
     */
    public function __construct(float $percentage, SubscriptionDiscountTypePercentage $type)
    {
        $this->percentage = $percentage;
        $this->type = $type;
    }
}