<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


/** Delivery method type. One of: `shipping`, `local-delivery`, `pickup`. */
enum SubscriptionType: string
{
    case Shipping = 'shipping';
    case LocalDelivery = 'local-delivery';
    case Pickup = 'pickup';
}
