<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


class SubscriptionItemDeliveryPolicy
{
    /**
     *
     * @var \Juo\AdminAPI\Models\Components\DeliveryPolicyIntervalDay|\Juo\AdminAPI\Models\Components\DeliveryPolicyIntervalWeek|\Juo\AdminAPI\Models\Components\DeliveryPolicyIntervalMonth|\Juo\AdminAPI\Models\Components\DeliveryPolicyIntervalYear $interval
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('interval')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Components\DeliveryPolicyIntervalDay|\Juo\AdminAPI\Models\Components\DeliveryPolicyIntervalWeek|\Juo\AdminAPI\Models\Components\DeliveryPolicyIntervalMonth|\Juo\AdminAPI\Models\Components\DeliveryPolicyIntervalYear')]
    public DeliveryPolicyIntervalDay|DeliveryPolicyIntervalWeek|DeliveryPolicyIntervalMonth|DeliveryPolicyIntervalYear $interval;

    /**
     *
     * @var int $intervalCount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('intervalCount')]
    public int $intervalCount;

    /**
     * $anchors
     *
     * @var array<\Juo\AdminAPI\Models\Components\DeliveryPolicyAnchor> $anchors
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('anchors')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Juo\AdminAPI\Models\Components\DeliveryPolicyAnchor>')]
    public array $anchors;

    /**
     * @param  \Juo\AdminAPI\Models\Components\DeliveryPolicyIntervalDay|\Juo\AdminAPI\Models\Components\DeliveryPolicyIntervalWeek|\Juo\AdminAPI\Models\Components\DeliveryPolicyIntervalMonth|\Juo\AdminAPI\Models\Components\DeliveryPolicyIntervalYear  $interval
     * @param  int  $intervalCount
     * @param  array<\Juo\AdminAPI\Models\Components\DeliveryPolicyAnchor>  $anchors
     * @phpstan-pure
     */
    public function __construct(DeliveryPolicyIntervalDay|DeliveryPolicyIntervalWeek|DeliveryPolicyIntervalMonth|DeliveryPolicyIntervalYear $interval, int $intervalCount, array $anchors)
    {
        $this->interval = $interval;
        $this->intervalCount = $intervalCount;
        $this->anchors = $anchors;
    }
}