<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


/** Subscription lifecycle status. `active`: billing runs on schedule; `paused`: billing suspended until resumed; `canceled`: permanently stopped (can be reactivated); `failed`: latest billing attempt failed; `expired`: reached configured end date; `merged`: consolidated into another subscription. */
enum SubscriptionStatus: string
{
    case Active = 'active';
    case Paused = 'paused';
    case Canceled = 'canceled';
    case Failed = 'failed';
    case Expired = 'expired';
    case Merged = 'merged';
}
