<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


class SubscriptionDiscount
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var \Juo\AdminAPI\Models\Components\SubscriptionDiscountResource $resource
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('resource')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Components\SubscriptionDiscountResource')]
    public SubscriptionDiscountResource $resource;

    /**
     *
     * @var \Juo\AdminAPI\Models\Components\SubscriptionDiscountTargetShipping|\Juo\AdminAPI\Models\Components\SubscriptionDiscountTargetLine $target
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('target')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Components\SubscriptionDiscountTargetShipping|\Juo\AdminAPI\Models\Components\SubscriptionDiscountTargetLine')]
    public SubscriptionDiscountTargetShipping|SubscriptionDiscountTargetLine $target;

    /**
     *
     * @var \Juo\AdminAPI\Models\Components\SubscriptionDiscountValueFixedAmount|\Juo\AdminAPI\Models\Components\SubscriptionDiscountValuePercentage $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Components\SubscriptionDiscountValueFixedAmount|\Juo\AdminAPI\Models\Components\SubscriptionDiscountValuePercentage')]
    public SubscriptionDiscountValueFixedAmount|SubscriptionDiscountValuePercentage $value;

    /**
     * The title of the discount shown to customers, typically displayed as a discount code.
     *
     * @var ?string $title
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('title')]
    public ?string $title;

    /**
     * The number of billing cycles for which this discount will be applied. After the recurring cycle limit is met the discount will be removed from the subscription.
     *
     * @var ?int $recurringCycleLimit
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('recurringCycleLimit')]
    public ?int $recurringCycleLimit;

    /**
     * @param  string  $id
     * @param  \Juo\AdminAPI\Models\Components\SubscriptionDiscountResource  $resource
     * @param  \Juo\AdminAPI\Models\Components\SubscriptionDiscountTargetShipping|\Juo\AdminAPI\Models\Components\SubscriptionDiscountTargetLine  $target
     * @param  \Juo\AdminAPI\Models\Components\SubscriptionDiscountValueFixedAmount|\Juo\AdminAPI\Models\Components\SubscriptionDiscountValuePercentage  $value
     * @param  ?string  $title
     * @param  ?int  $recurringCycleLimit
     * @phpstan-pure
     */
    public function __construct(string $id, SubscriptionDiscountResource $resource, SubscriptionDiscountTargetShipping|SubscriptionDiscountTargetLine $target, SubscriptionDiscountValueFixedAmount|SubscriptionDiscountValuePercentage $value, ?string $title = null, ?int $recurringCycleLimit = null)
    {
        $this->id = $id;
        $this->resource = $resource;
        $this->target = $target;
        $this->value = $value;
        $this->title = $title;
        $this->recurringCycleLimit = $recurringCycleLimit;
    }
}