<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


class TransitionItem2
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var \Juo\AdminAPI\Models\Components\TransitionLeft2 $left
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('left')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Components\TransitionLeft2')]
    public TransitionLeft2 $left;

    /**
     *
     * @var \Juo\AdminAPI\Models\Components\TransitionOperatorEquals2|\Juo\AdminAPI\Models\Components\TransitionOperatorNotEquals2|\Juo\AdminAPI\Models\Components\TransitionOperatorGreaterThan2|\Juo\AdminAPI\Models\Components\TransitionOperatorGreaterThanOrEqual2|\Juo\AdminAPI\Models\Components\TransitionOperatorLessThan2|\Juo\AdminAPI\Models\Components\TransitionOperatorLessThanOrEqual2|\Juo\AdminAPI\Models\Components\TransitionOperatorIs2|\Juo\AdminAPI\Models\Components\TransitionOperatorIsNot2|\Juo\AdminAPI\Models\Components\TransitionOperatorIsOneOf2|\Juo\AdminAPI\Models\Components\TransitionOperatorIsNotOneOf2|\Juo\AdminAPI\Models\Components\TransitionOperatorContains2|\Juo\AdminAPI\Models\Components\TransitionOperatorDoesNotContain2|\Juo\AdminAPI\Models\Components\TransitionOperatorIsBefore2|\Juo\AdminAPI\Models\Components\TransitionOperatorIsAfter2|\Juo\AdminAPI\Models\Components\TransitionOperatorIsOn2|\Juo\AdminAPI\Models\Components\TransitionOperatorIsOnOrBefore2|\Juo\AdminAPI\Models\Components\TransitionOperatorIsOnOrAfter2|\Juo\AdminAPI\Models\Components\TransitionOperatorIsEmpty2|\Juo\AdminAPI\Models\Components\TransitionOperatorIsNotEmpty2|\Juo\AdminAPI\Models\Components\TransitionOperatorContainsWhere2|\Juo\AdminAPI\Models\Components\TransitionOperatorDoesNotContainWhere2 $operator
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('operator')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Components\TransitionOperatorEquals2|\Juo\AdminAPI\Models\Components\TransitionOperatorNotEquals2|\Juo\AdminAPI\Models\Components\TransitionOperatorGreaterThan2|\Juo\AdminAPI\Models\Components\TransitionOperatorGreaterThanOrEqual2|\Juo\AdminAPI\Models\Components\TransitionOperatorLessThan2|\Juo\AdminAPI\Models\Components\TransitionOperatorLessThanOrEqual2|\Juo\AdminAPI\Models\Components\TransitionOperatorIs2|\Juo\AdminAPI\Models\Components\TransitionOperatorIsNot2|\Juo\AdminAPI\Models\Components\TransitionOperatorIsOneOf2|\Juo\AdminAPI\Models\Components\TransitionOperatorIsNotOneOf2|\Juo\AdminAPI\Models\Components\TransitionOperatorContains2|\Juo\AdminAPI\Models\Components\TransitionOperatorDoesNotContain2|\Juo\AdminAPI\Models\Components\TransitionOperatorIsBefore2|\Juo\AdminAPI\Models\Components\TransitionOperatorIsAfter2|\Juo\AdminAPI\Models\Components\TransitionOperatorIsOn2|\Juo\AdminAPI\Models\Components\TransitionOperatorIsOnOrBefore2|\Juo\AdminAPI\Models\Components\TransitionOperatorIsOnOrAfter2|\Juo\AdminAPI\Models\Components\TransitionOperatorIsEmpty2|\Juo\AdminAPI\Models\Components\TransitionOperatorIsNotEmpty2|\Juo\AdminAPI\Models\Components\TransitionOperatorContainsWhere2|\Juo\AdminAPI\Models\Components\TransitionOperatorDoesNotContainWhere2')]
    public TransitionOperatorEquals2|TransitionOperatorNotEquals2|TransitionOperatorGreaterThan2|TransitionOperatorGreaterThanOrEqual2|TransitionOperatorLessThan2|TransitionOperatorLessThanOrEqual2|TransitionOperatorIs2|TransitionOperatorIsNot2|TransitionOperatorIsOneOf2|TransitionOperatorIsNotOneOf2|TransitionOperatorContains2|TransitionOperatorDoesNotContain2|TransitionOperatorIsBefore2|TransitionOperatorIsAfter2|TransitionOperatorIsOn2|TransitionOperatorIsOnOrBefore2|TransitionOperatorIsOnOrAfter2|TransitionOperatorIsEmpty2|TransitionOperatorIsNotEmpty2|TransitionOperatorContainsWhere2|TransitionOperatorDoesNotContainWhere2 $operator;

    /**
     *
     * @var \Juo\AdminAPI\Models\Components\TransitionRight2 $right
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('right')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Components\TransitionRight2')]
    public TransitionRight2 $right;

    /**
     * @param  string  $id
     * @param  \Juo\AdminAPI\Models\Components\TransitionLeft2  $left
     * @param  \Juo\AdminAPI\Models\Components\TransitionOperatorEquals2|\Juo\AdminAPI\Models\Components\TransitionOperatorNotEquals2|\Juo\AdminAPI\Models\Components\TransitionOperatorGreaterThan2|\Juo\AdminAPI\Models\Components\TransitionOperatorGreaterThanOrEqual2|\Juo\AdminAPI\Models\Components\TransitionOperatorLessThan2|\Juo\AdminAPI\Models\Components\TransitionOperatorLessThanOrEqual2|\Juo\AdminAPI\Models\Components\TransitionOperatorIs2|\Juo\AdminAPI\Models\Components\TransitionOperatorIsNot2|\Juo\AdminAPI\Models\Components\TransitionOperatorIsOneOf2|\Juo\AdminAPI\Models\Components\TransitionOperatorIsNotOneOf2|\Juo\AdminAPI\Models\Components\TransitionOperatorContains2|\Juo\AdminAPI\Models\Components\TransitionOperatorDoesNotContain2|\Juo\AdminAPI\Models\Components\TransitionOperatorIsBefore2|\Juo\AdminAPI\Models\Components\TransitionOperatorIsAfter2|\Juo\AdminAPI\Models\Components\TransitionOperatorIsOn2|\Juo\AdminAPI\Models\Components\TransitionOperatorIsOnOrBefore2|\Juo\AdminAPI\Models\Components\TransitionOperatorIsOnOrAfter2|\Juo\AdminAPI\Models\Components\TransitionOperatorIsEmpty2|\Juo\AdminAPI\Models\Components\TransitionOperatorIsNotEmpty2|\Juo\AdminAPI\Models\Components\TransitionOperatorContainsWhere2|\Juo\AdminAPI\Models\Components\TransitionOperatorDoesNotContainWhere2  $operator
     * @param  \Juo\AdminAPI\Models\Components\TransitionRight2  $right
     * @phpstan-pure
     */
    public function __construct(string $id, TransitionLeft2 $left, TransitionOperatorEquals2|TransitionOperatorNotEquals2|TransitionOperatorGreaterThan2|TransitionOperatorGreaterThanOrEqual2|TransitionOperatorLessThan2|TransitionOperatorLessThanOrEqual2|TransitionOperatorIs2|TransitionOperatorIsNot2|TransitionOperatorIsOneOf2|TransitionOperatorIsNotOneOf2|TransitionOperatorContains2|TransitionOperatorDoesNotContain2|TransitionOperatorIsBefore2|TransitionOperatorIsAfter2|TransitionOperatorIsOn2|TransitionOperatorIsOnOrBefore2|TransitionOperatorIsOnOrAfter2|TransitionOperatorIsEmpty2|TransitionOperatorIsNotEmpty2|TransitionOperatorContainsWhere2|TransitionOperatorDoesNotContainWhere2 $operator, TransitionRight2 $right)
    {
        $this->id = $id;
        $this->left = $left;
        $this->operator = $operator;
        $this->right = $right;
    }
}