<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


class TransitionGroup2
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var \Juo\AdminAPI\Models\Components\TransitionLogicAnd2|\Juo\AdminAPI\Models\Components\TransitionLogicOr2 $logic
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('logic')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Components\TransitionLogicAnd2|\Juo\AdminAPI\Models\Components\TransitionLogicOr2')]
    public TransitionLogicAnd2|TransitionLogicOr2 $logic;

    /**
     * $items
     *
     * @var array<\Juo\AdminAPI\Models\Components\TransitionItem2> $items
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('items')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Juo\AdminAPI\Models\Components\TransitionItem2>')]
    public array $items;

    /**
     * @param  string  $id
     * @param  \Juo\AdminAPI\Models\Components\TransitionLogicAnd2|\Juo\AdminAPI\Models\Components\TransitionLogicOr2  $logic
     * @param  array<\Juo\AdminAPI\Models\Components\TransitionItem2>  $items
     * @phpstan-pure
     */
    public function __construct(string $id, TransitionLogicAnd2|TransitionLogicOr2 $logic, array $items)
    {
        $this->id = $id;
        $this->logic = $logic;
        $this->items = $items;
    }
}