<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


class TransitionItem1
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var \Juo\AdminAPI\Models\Components\TransitionLeft1 $left
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('left')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Components\TransitionLeft1')]
    public TransitionLeft1 $left;

    /**
     *
     * @var \Juo\AdminAPI\Models\Components\TransitionOperatorEquals1|\Juo\AdminAPI\Models\Components\TransitionOperatorNotEquals1|\Juo\AdminAPI\Models\Components\TransitionOperatorGreaterThan1|\Juo\AdminAPI\Models\Components\TransitionOperatorGreaterThanOrEqual1|\Juo\AdminAPI\Models\Components\TransitionOperatorLessThan1|\Juo\AdminAPI\Models\Components\TransitionOperatorLessThanOrEqual1|\Juo\AdminAPI\Models\Components\TransitionOperatorIs1|\Juo\AdminAPI\Models\Components\TransitionOperatorIsNot1|\Juo\AdminAPI\Models\Components\TransitionOperatorIsOneOf1|\Juo\AdminAPI\Models\Components\TransitionOperatorIsNotOneOf1|\Juo\AdminAPI\Models\Components\TransitionOperatorContains1|\Juo\AdminAPI\Models\Components\TransitionOperatorDoesNotContain1|\Juo\AdminAPI\Models\Components\TransitionOperatorIsBefore1|\Juo\AdminAPI\Models\Components\TransitionOperatorIsAfter1|\Juo\AdminAPI\Models\Components\TransitionOperatorIsOn1|\Juo\AdminAPI\Models\Components\TransitionOperatorIsOnOrBefore1|\Juo\AdminAPI\Models\Components\TransitionOperatorIsOnOrAfter1|\Juo\AdminAPI\Models\Components\TransitionOperatorIsEmpty1|\Juo\AdminAPI\Models\Components\TransitionOperatorIsNotEmpty1|\Juo\AdminAPI\Models\Components\TransitionOperatorContainsWhere1|\Juo\AdminAPI\Models\Components\TransitionOperatorDoesNotContainWhere1 $operator
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('operator')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Components\TransitionOperatorEquals1|\Juo\AdminAPI\Models\Components\TransitionOperatorNotEquals1|\Juo\AdminAPI\Models\Components\TransitionOperatorGreaterThan1|\Juo\AdminAPI\Models\Components\TransitionOperatorGreaterThanOrEqual1|\Juo\AdminAPI\Models\Components\TransitionOperatorLessThan1|\Juo\AdminAPI\Models\Components\TransitionOperatorLessThanOrEqual1|\Juo\AdminAPI\Models\Components\TransitionOperatorIs1|\Juo\AdminAPI\Models\Components\TransitionOperatorIsNot1|\Juo\AdminAPI\Models\Components\TransitionOperatorIsOneOf1|\Juo\AdminAPI\Models\Components\TransitionOperatorIsNotOneOf1|\Juo\AdminAPI\Models\Components\TransitionOperatorContains1|\Juo\AdminAPI\Models\Components\TransitionOperatorDoesNotContain1|\Juo\AdminAPI\Models\Components\TransitionOperatorIsBefore1|\Juo\AdminAPI\Models\Components\TransitionOperatorIsAfter1|\Juo\AdminAPI\Models\Components\TransitionOperatorIsOn1|\Juo\AdminAPI\Models\Components\TransitionOperatorIsOnOrBefore1|\Juo\AdminAPI\Models\Components\TransitionOperatorIsOnOrAfter1|\Juo\AdminAPI\Models\Components\TransitionOperatorIsEmpty1|\Juo\AdminAPI\Models\Components\TransitionOperatorIsNotEmpty1|\Juo\AdminAPI\Models\Components\TransitionOperatorContainsWhere1|\Juo\AdminAPI\Models\Components\TransitionOperatorDoesNotContainWhere1')]
    public TransitionOperatorEquals1|TransitionOperatorNotEquals1|TransitionOperatorGreaterThan1|TransitionOperatorGreaterThanOrEqual1|TransitionOperatorLessThan1|TransitionOperatorLessThanOrEqual1|TransitionOperatorIs1|TransitionOperatorIsNot1|TransitionOperatorIsOneOf1|TransitionOperatorIsNotOneOf1|TransitionOperatorContains1|TransitionOperatorDoesNotContain1|TransitionOperatorIsBefore1|TransitionOperatorIsAfter1|TransitionOperatorIsOn1|TransitionOperatorIsOnOrBefore1|TransitionOperatorIsOnOrAfter1|TransitionOperatorIsEmpty1|TransitionOperatorIsNotEmpty1|TransitionOperatorContainsWhere1|TransitionOperatorDoesNotContainWhere1 $operator;

    /**
     *
     * @var \Juo\AdminAPI\Models\Components\TransitionRight1 $right
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('right')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Components\TransitionRight1')]
    public TransitionRight1 $right;

    /**
     * @param  string  $id
     * @param  \Juo\AdminAPI\Models\Components\TransitionLeft1  $left
     * @param  \Juo\AdminAPI\Models\Components\TransitionOperatorEquals1|\Juo\AdminAPI\Models\Components\TransitionOperatorNotEquals1|\Juo\AdminAPI\Models\Components\TransitionOperatorGreaterThan1|\Juo\AdminAPI\Models\Components\TransitionOperatorGreaterThanOrEqual1|\Juo\AdminAPI\Models\Components\TransitionOperatorLessThan1|\Juo\AdminAPI\Models\Components\TransitionOperatorLessThanOrEqual1|\Juo\AdminAPI\Models\Components\TransitionOperatorIs1|\Juo\AdminAPI\Models\Components\TransitionOperatorIsNot1|\Juo\AdminAPI\Models\Components\TransitionOperatorIsOneOf1|\Juo\AdminAPI\Models\Components\TransitionOperatorIsNotOneOf1|\Juo\AdminAPI\Models\Components\TransitionOperatorContains1|\Juo\AdminAPI\Models\Components\TransitionOperatorDoesNotContain1|\Juo\AdminAPI\Models\Components\TransitionOperatorIsBefore1|\Juo\AdminAPI\Models\Components\TransitionOperatorIsAfter1|\Juo\AdminAPI\Models\Components\TransitionOperatorIsOn1|\Juo\AdminAPI\Models\Components\TransitionOperatorIsOnOrBefore1|\Juo\AdminAPI\Models\Components\TransitionOperatorIsOnOrAfter1|\Juo\AdminAPI\Models\Components\TransitionOperatorIsEmpty1|\Juo\AdminAPI\Models\Components\TransitionOperatorIsNotEmpty1|\Juo\AdminAPI\Models\Components\TransitionOperatorContainsWhere1|\Juo\AdminAPI\Models\Components\TransitionOperatorDoesNotContainWhere1  $operator
     * @param  \Juo\AdminAPI\Models\Components\TransitionRight1  $right
     * @phpstan-pure
     */
    public function __construct(string $id, TransitionLeft1 $left, TransitionOperatorEquals1|TransitionOperatorNotEquals1|TransitionOperatorGreaterThan1|TransitionOperatorGreaterThanOrEqual1|TransitionOperatorLessThan1|TransitionOperatorLessThanOrEqual1|TransitionOperatorIs1|TransitionOperatorIsNot1|TransitionOperatorIsOneOf1|TransitionOperatorIsNotOneOf1|TransitionOperatorContains1|TransitionOperatorDoesNotContain1|TransitionOperatorIsBefore1|TransitionOperatorIsAfter1|TransitionOperatorIsOn1|TransitionOperatorIsOnOrBefore1|TransitionOperatorIsOnOrAfter1|TransitionOperatorIsEmpty1|TransitionOperatorIsNotEmpty1|TransitionOperatorContainsWhere1|TransitionOperatorDoesNotContainWhere1 $operator, TransitionRight1 $right)
    {
        $this->id = $id;
        $this->left = $left;
        $this->operator = $operator;
        $this->right = $right;
    }
}