<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


class TransitionAuto
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var string $targetStepId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('targetStepId')]
    public string $targetStepId;

    /**
     *
     * @var \Juo\AdminAPI\Models\Components\TypeAuto $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Components\TypeAuto')]
    public TypeAuto $type;

    /**
     *
     * @var ?\Juo\AdminAPI\Models\Components\TransitionConditions1 $conditions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('conditions')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Components\TransitionConditions1|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?TransitionConditions1 $conditions = null;

    /**
     * @param  string  $id
     * @param  string  $targetStepId
     * @param  \Juo\AdminAPI\Models\Components\TypeAuto  $type
     * @param  ?\Juo\AdminAPI\Models\Components\TransitionConditions1  $conditions
     * @phpstan-pure
     */
    public function __construct(string $id, string $targetStepId, TypeAuto $type, ?TransitionConditions1 $conditions = null)
    {
        $this->id = $id;
        $this->targetStepId = $targetStepId;
        $this->type = $type;
        $this->conditions = $conditions;
    }
}