<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


class TransitionConditions1
{
    /**
     * $groups
     *
     * @var array<\Juo\AdminAPI\Models\Components\TransitionGroup1> $groups
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('groups')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Juo\AdminAPI\Models\Components\TransitionGroup1>')]
    public array $groups;

    /**
     *
     * @var \Juo\AdminAPI\Models\Components\TransitionRootLogicAnd1|\Juo\AdminAPI\Models\Components\TransitionRootLogicOr1 $rootLogic
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('rootLogic')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Components\TransitionRootLogicAnd1|\Juo\AdminAPI\Models\Components\TransitionRootLogicOr1')]
    public TransitionRootLogicAnd1|TransitionRootLogicOr1 $rootLogic;

    /**
     * @param  array<\Juo\AdminAPI\Models\Components\TransitionGroup1>  $groups
     * @param  \Juo\AdminAPI\Models\Components\TransitionRootLogicAnd1|\Juo\AdminAPI\Models\Components\TransitionRootLogicOr1  $rootLogic
     * @phpstan-pure
     */
    public function __construct(array $groups, TransitionRootLogicAnd1|TransitionRootLogicOr1 $rootLogic)
    {
        $this->groups = $groups;
        $this->rootLogic = $rootLogic;
    }
}