<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


class TransitionTimeout
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var string $targetStepId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('targetStepId')]
    public string $targetStepId;

    /**
     *
     * @var \Juo\AdminAPI\Models\Components\TypeTimeout $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Components\TypeTimeout')]
    public TypeTimeout $type;

    /**
     *
     * @var float $timeout
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('timeout')]
    public float $timeout;

    /**
     * @param  string  $id
     * @param  string  $targetStepId
     * @param  \Juo\AdminAPI\Models\Components\TypeTimeout  $type
     * @param  float  $timeout
     * @phpstan-pure
     */
    public function __construct(string $id, string $targetStepId, TypeTimeout $type, float $timeout)
    {
        $this->id = $id;
        $this->targetStepId = $targetStepId;
        $this->type = $type;
        $this->timeout = $timeout;
    }
}