<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


enum TransitionOperatorGreaterThanOrEqual2: string
{
    case GreaterThanOrEqual = 'greater_than_or_equal';
}
