<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


class TriggerConditions
{
    /**
     * $groups
     *
     * @var array<\Juo\AdminAPI\Models\Components\TriggerGroup> $groups
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('groups')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Juo\AdminAPI\Models\Components\TriggerGroup>')]
    public array $groups;

    /**
     *
     * @var \Juo\AdminAPI\Models\Components\RootLogicTriggerAnd|\Juo\AdminAPI\Models\Components\RootLogicTriggerOr $rootLogic
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('rootLogic')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Components\RootLogicTriggerAnd|\Juo\AdminAPI\Models\Components\RootLogicTriggerOr')]
    public RootLogicTriggerAnd|RootLogicTriggerOr $rootLogic;

    /**
     * @param  array<\Juo\AdminAPI\Models\Components\TriggerGroup>  $groups
     * @param  \Juo\AdminAPI\Models\Components\RootLogicTriggerAnd|\Juo\AdminAPI\Models\Components\RootLogicTriggerOr  $rootLogic
     * @phpstan-pure
     */
    public function __construct(array $groups, RootLogicTriggerAnd|RootLogicTriggerOr $rootLogic)
    {
        $this->groups = $groups;
        $this->rootLogic = $rootLogic;
    }
}