<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


class WorkflowRunSummary
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var \Juo\AdminAPI\Models\Components\WorkflowRunSummaryResource $resource
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('resource')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Components\WorkflowRunSummaryResource')]
    public WorkflowRunSummaryResource $resource;

    /**
     *
     * @var string $customerId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('customerId')]
    public string $customerId;

    /**
     *
     * @var string $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    public string $status;

    /**
     *
     * @var float $workflowVersion
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('workflowVersion')]
    public float $workflowVersion;

    /**
     *
     * @var \DateTime $startedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('startedAt')]
    public \DateTime $startedAt;

    /**
     *
     * @var \DateTime $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updatedAt')]
    public \DateTime $updatedAt;

    /**
     *
     * @var ?\DateTime $completedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('completedAt')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $completedAt = null;

    /**
     * @param  string  $id
     * @param  \Juo\AdminAPI\Models\Components\WorkflowRunSummaryResource  $resource
     * @param  string  $customerId
     * @param  string  $status
     * @param  float  $workflowVersion
     * @param  \DateTime  $startedAt
     * @param  \DateTime  $updatedAt
     * @param  ?\DateTime  $completedAt
     * @phpstan-pure
     */
    public function __construct(string $id, WorkflowRunSummaryResource $resource, string $customerId, string $status, float $workflowVersion, \DateTime $startedAt, \DateTime $updatedAt, ?\DateTime $completedAt = null)
    {
        $this->id = $id;
        $this->resource = $resource;
        $this->customerId = $customerId;
        $this->status = $status;
        $this->workflowVersion = $workflowVersion;
        $this->startedAt = $startedAt;
        $this->updatedAt = $updatedAt;
        $this->completedAt = $completedAt;
    }
}