<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


enum WorkflowRunStateStatus: string
{
    case Running = 'running';
    case WaitingInteraction = 'waiting_interaction';
    case Completed = 'completed';
    case Failed = 'failed';
    case Cancelled = 'cancelled';
}
