<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


class WorkflowVariant
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     *
     * @var int $trafficPercentage
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('trafficPercentage')]
    public int $trafficPercentage;

    /**
     * @param  string  $id
     * @param  string  $name
     * @param  int  $trafficPercentage
     * @phpstan-pure
     */
    public function __construct(string $id, string $name, int $trafficPercentage)
    {
        $this->id = $id;
        $this->name = $name;
        $this->trafficPercentage = $trafficPercentage;
    }
}