<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI\Models\Components;


class WorkflowRunState
{
    /**
     *
     * @var string $workflowId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('workflowId')]
    public string $workflowId;

    /**
     *
     * @var float $workflowVersion
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('workflowVersion')]
    public float $workflowVersion;

    /**
     *
     * @var string $runId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('runId')]
    public string $runId;

    /**
     *
     * @var float $runVersion
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('runVersion')]
    public float $runVersion;

    /**
     *
     * @var \Juo\AdminAPI\Models\Components\WorkflowRunStateStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Components\WorkflowRunStateStatus')]
    public WorkflowRunStateStatus $status;

    /**
     *
     * @var ?\Juo\AdminAPI\Models\Components\PendingInteraction $pendingInteraction
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pendingInteraction')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Components\PendingInteraction|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PendingInteraction $pendingInteraction = null;

    /**
     * $result
     *
     * @var ?array<string, mixed> $result
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('result')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $result = null;

    /**
     *
     * @var ?\Juo\AdminAPI\Models\Components\Error $error
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('error')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Components\Error|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Error $error = null;

    /**
     *
     * @var ?\Juo\AdminAPI\Models\Components\CompletionData $completionData
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('completionData')]
    #[\Speakeasy\Serializer\Annotation\Type('\Juo\AdminAPI\Models\Components\CompletionData|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CompletionData $completionData = null;

    /**
     * @param  string  $workflowId
     * @param  float  $workflowVersion
     * @param  string  $runId
     * @param  float  $runVersion
     * @param  \Juo\AdminAPI\Models\Components\WorkflowRunStateStatus  $status
     * @param  ?\Juo\AdminAPI\Models\Components\PendingInteraction  $pendingInteraction
     * @param  ?array<string, mixed>  $result
     * @param  ?\Juo\AdminAPI\Models\Components\Error  $error
     * @param  ?\Juo\AdminAPI\Models\Components\CompletionData  $completionData
     * @phpstan-pure
     */
    public function __construct(string $workflowId, float $workflowVersion, string $runId, float $runVersion, WorkflowRunStateStatus $status, ?PendingInteraction $pendingInteraction = null, ?array $result = null, ?Error $error = null, ?CompletionData $completionData = null)
    {
        $this->workflowId = $workflowId;
        $this->workflowVersion = $workflowVersion;
        $this->runId = $runId;
        $this->runVersion = $runVersion;
        $this->status = $status;
        $this->pendingInteraction = $pendingInteraction;
        $this->result = $result;
        $this->error = $error;
        $this->completionData = $completionData;
    }
}