<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Juo\AdminAPI;

use Juo\AdminAPI\Utils\Retry;

/**
 * JuoBuilder is used to configure and build an instance of the SDK.
 */
class JuoBuilder
{
    public function __construct(
        private SDKConfiguration $sdkConfig = new SDKConfiguration(),
    ) {
    }

    /**
     * setClient allows setting a custom Guzzle client for the SDK to make requests with.
     *
     * @param  \GuzzleHttp\ClientInterface  $client
     * @return JuoBuilder
     */
    public function setClient(\GuzzleHttp\ClientInterface $client): JuoBuilder
    {
        $this->sdkConfig->client = $client;

        return $this;
    }

    /**
     * setSecurity is used to configure the security required for the SDK.
     *
     * @param  Models\Components\Security  $security
     * @return JuoBuilder
     */
    public function setSecurity(Models\Components\Security $security): JuoBuilder
    {
        $this->sdkConfig->securitySource = fn () => $security;

        return $this;
    }

    /**
     * setSecuritySource is usd to configure the security required for the SDK.
     * unlike setSecurity, setSecuritySource accepts a closure that will be called to retrieve the security information.
     *
     * @param  pure-Closure(): Models\Components\Security  $securitySource
     * @return JuoBuilder
     */
    public function setSecuritySource(\Closure $securitySource): JuoBuilder
    {
        $this->sdkConfig->securitySource = $securitySource;

        return $this;
    }

    /**
     * setServerUrl is used to configure the server URL for the SDK, and optionally template any parameters in the URL.
     *
     * @param  string  $serverUrl
     * @param  array<string, string>  $params
     * @return JuoBuilder
     */
    public function setServerUrl(string $serverUrl, ?array $params = null): JuoBuilder
    {
        $this->sdkConfig->serverUrl = Utils\Utils::templateUrl($serverUrl, $params);

        return $this;
    }

    /**
     * setServer is used to configure the server for the SDK
     *
     * @param  int  $serverIdx
     * @return JuoBuilder
     */
    public function setServerIndex(int $serverIdx): JuoBuilder
    {
        $this->sdkConfig->serverIndex = $serverIdx;

        return $this;
    }
    /**
     * setTenant is used to configure the tenant parameter for the SDK.
     *
     * @param  string  $tenant
     * @return JuoBuilder
     */
    public function setTenant(string $tenant): JuoBuilder
    {
        if (! array_key_exists('header', $this->sdkConfig->globals['parameters'])) {
            $this->sdkConfig->globals['parameters']['header'] = [];
        }

        $this->sdkConfig->globals['parameters']['header']['tenant'] = $tenant;

        return $this;
    }

    public function setRetryConfig(Retry\RetryConfig $config): JuoBuilder
    {
        $this->sdkConfig->retryConfig = $config;

        return $this;
    }

    /**
     * build is used to build the SDK with any of the configured options.
     *
     * @return Juo
     */
    public function build(): Juo
    {
        if ($this->sdkConfig->client === null) {
            $this->sdkConfig->client = new \GuzzleHttp\Client([
                'timeout' => 60,
            ]);
        }

        $this->sdkConfig->defaultClient = $this->sdkConfig->client;
        if ($this->sdkConfig->hasSecurity()) {
            $this->sdkConfig->client = Utils\Utils::configureSecurityClient($this->sdkConfig->client, $this->sdkConfig->getSecurity());
        }

        return new Juo($this->sdkConfig);
    }
}